// Application MetaData Action Constants
// eslint-disable-next-line import/prefer-default-export

export const API_NOT_INVOKED = 0;
export const API_INVOKED = 1;
export const API_DATA_LOADED = 2;
export const API_ERRORED = 3;

// Store Group Keys
export const KEY_METADATA = "metaData";
export const KEY_TECHNICIAN_DATA = "technicianData";
export const KEY_EVENTS_DATA = "eventsData";
export const KEY_TEAMTERITORY_DATA = "technicianData";
export const KEY_VIEW_DATA = "viewData";
export const KEY_WORKORDER_DATA = "workOrderData";
export const KEY_DISPATCHER_DATA = "dispatcherData";

// Request Identifier Keys
export const KEY_WORKORDERS = "workOrders";
export const KEY_NEXT_WORKORDERS = "nextworkOrders";
export const KEY_PREV_WORKORDERS = "prevworkOrders";
export const KEY_RECORDS = "records";
export const KEY_DISPLAY_TAGS = "displayTags";
export const KEY_VIEWS = "views";
export const KEY_TIMEZONES = "timeZones";
export const KEY_USER_TIMEZONE = "userTimezone";
export const KEY_APP_SETTINGS = "appSettings";
export const KEY_USER_SETTINGS = "userSettings";
export const KEY_WORKORDER_FIELD_LIST = "workOrderFields";
export const KEY_VIEW_WORKORDER_COUNT = "viewWorkOrderCount";
export const KEY_VIEW_DEFINITION = "viewDefinition";
export const KEY_MAP_VIEW_DATA = "mapViewData";
export const KEY_TECHNICIANS = "technicians";
export const KEY_TECHNICIANS_DETAILS = "techniciansDetails";
export const KEY_TECHNICIAN_WORKING_HOURS = "technicianWorkingHours";
export const KEY_TECHNICIANS_WORKING_HOURS = "techniciansWorkingHours";
export const KEY_TECHNICIANS_METADATA = "technicianFields";
export const KEY_TEAM_METADATA = "serviceTeamFields";
export const KEY_EVENTS_METADATA = "eventFields";
export const KEY_EVENTS = "events";
export const KEY_EVENT_IDS = "eventIds";
export const KEY_LOAD_EVENT_IDS = "loadEventIds";
export const KEY_EVENTS_HOVER = "eventsHoverInfo";
export const KEY_EVENTS_ON_EXPAND = "eventsOnExpand";
export const KEY_TECH_SKILLS = "techSkills";
export const KEY_WO_MATCH_SKILLS = "woMatchSkills";
export const KEY_SEARCH_TECH = "searchTeachnicians";
export const KEY_EVENT_SUBJECT = "getEventSubject";
export const KEY_CREAT_EVENT = "KEY_CREAT_EVENT";
export const KEY_UPDATE_EVENT = "KEY_UPDATE_EVENT";
export const KEY_ADV_TECH_SEARCH = "advTechSearch";
export const KEY_DELTA_WORK_ORDER = "deltaWorkOrder";
export const KEY_FILTER_TECHNICIAN = "filterTechnician";
export const KEY_DEPLOY_USER_SETTINGS = "deployusersettings";
export const KEY_WORKORDER_EVENTS = "workorderEvents";
export const KEY_MULTIASSIGN_EVENTS = "multiAssignEvents";
export const KEY_MULTIASSIGN_UPDATE = "multiAssignUpdate";
export const KEY_EVENT_BUSINESS_HOUR = "eventBusinessHour";
export const KEY_FETCH_DELTA_EVENTS = "deltaEvents";
export const KEY_EVENTS_LAST_MODIFIED_EVENT = "lastModifiedEvent";

// Action Types
export const GET_METADATA = "GET_METADATA";
export const GET_DISPLAY_TAGS = "GET_DISPLAY_TAGS";
export const GET_APP_SETTINGS = "GET_APP_SETTINGS";
export const GET_USER_SETTINGS = "GET_USER_SETTINGS";
export const GET_WORKORDER_FIELD_LIST = "GET_WORKORDER_FIELD_LIST";
export const GET_WORKORDER = "GET_WORKORDER";
export const GET_WORKORDERS = "GET_WORKORDERS";
export const GET_NEXTPREV_WORKORDERS = "GET_NEXTPREV_WORKORDERS";
export const GET_VIEW_DEFINITION = "GET_VIEW_DEFINITION";
export const GET_MAP_VIEW_DATA = "GET_MAP_VIEW_DATA";
export const GET_VIEW_WORKORDER_COUNT = "GET_VIEW_WORKORDER_COUNT";
export const GET_TECHNICIANS = "GET_TECHNICIANS";
export const GET_TECHNICIANS_DETAILS = "GET_TECHNICIANS_DETAILS";
export const UPDATE_TECHNICIAN_TREEDATA = "UPDATE_TECHNICIAN_TREEDATA";
export const GET_TECHNICIANS_WORKING_HOURS = "GET_TECHNICIANS_WORKING_HOURS";
export const GET_TECHNICIANS_METADATA = "GET TECHNICIANS META DATA";
export const GET_TEAM_METADATA = "GET TEAM META DATA";
export const GET_EVENTS = "GET_EVENTS";
export const GET_EVENT_HOVER_RULES = "GET_EVENT_HOVER_RULES";
export const GET_EVENTS_AFTER_LAUNCH = "GET_EVENTS_AFTER_LAUNCH";
export const START_EVENTS_AFTER_LAUNCH = "START_EVENTS_AFTER_LAUNCH";
export const GET_EVENT_SUBJECT = "GET_EVENT_SUBJECT";
export const CREAT_EVENT = "CREAT_EVENT";
export const CREAT_EVENT_FOR_TREE = "CREAT_EVENT_FOR_TREE";
export const CREAT_LJS_EVENT = "CREAT_LJS_EVENT";
export const FETCH_WO_EVENT_INFO = "FETCH_WO_EVENT_INFO";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const UPDATE_TECH_CHANGE_EVENT = "UPDATE_TECH_CHANGE_EVENT";
export const GET_EVENTS_METADATA = "GET EVENTS META DATA";
export const GET_TECHNICIAN_SKILLS = "GET_TECHNICIAN_SKILLS";
export const GET_WO_MATCHING_TECH_SKILLS = "GET_WO_MATCHING_TECH_SKILLS";
export const GET_SEARCH_TECH = "GET_SEARCH_TECHNICIANS";
export const GET_DELTA_WORK_ORDER = "GET_DELTA_WORK_ORDER";
export const UPDATE_SINGLE_WO = "UPDATE_SINGLE_WO";
export const GET_LIST_OF_TECH_SCHEDULED = "GET_LIST_OF_TECH_SCHEDULED";
export const FETCH_ALL_EVENTS = "FETCH_ALL_EVENTS";
export const GET_DISPATCHER_LIST = "GET_DISPATCHER_LIST";
export const POST_USER_SETTINGS = "POST_USER_SETTINGS";
export const GET_WORKORDER_EVENTS = "GET_WORKORDER_EVENTS";
export const GET_EVENT_BUSINESS_HOUR = "GET_EVENT_BUSINESS_HOUR";
export const UPDATE_TECHNICIAN_WORKING_HOURS =
  "UPDATE_TECHNICIAN_WORKING_HOURS";
export const GET_EVENT_IDS = "GET_EVENT_IDS";
export const LOAD_EVENT_IDS = "LOAD_EVENT_IDS";
export const LOAD_ALL_EVENT_IDS = "LOAD_ALL_EVENT_IDS";
export const LOAD_WIDE_RANGE_EVENTS = "LOAD_WIDE_RANGE_EVENTS";
export const FETCH_DELTA_EVENTS = "FETCH_DELTA_EVENTS";
export const EVENTS_FETCH_DELTA_EVENTS = "EVENTS_FETCH_DELTA_EVENTS";
export const EVENTS_LAST_MODIFIED_EVENT = "EVENTS_LAST_MODIFIED_EVENT";
export const DELETE_DELTA_EVENTS = "DELETE_DELTA_EVENTS";

// Grid State Change Action Types
export const DEFAULT_VIEW_CHANGED = "DEFAULT_VIEW_CHANGED";
export const VIEW_SELECTION_CHANGED = "VIEW_SELECTION_CHANGED";
export const FILTER_COLUMN_CHANGED = "FILTER_COLUMN_CHANGED";
export const FILTER_TEXT_CHANGED = "FILTER_TEXT_CHANGED";
export const STATUS_FILTER_CHANGED = "STATUS_FILTER_CHANGED";
export const PAGE_SELECTION_CHANGED = "PAGE_SELECTION_CHANGED";
export const SORT_ORDER_CHANGED = "SORT_ORDER_CHANGED";
export const ROW_SELECTION_CHANGED = "ROW_SELECTION_CHANGED";
export const GRID_COLUMN_CHANGED = "GRID_COLUMN_CHANGED";
export const GRID_COLUMN_RESIZED = "GRID_COLUMN_RESIZED";
export const COLOR_RULE_CHANGED = "COLOR_RULE_CHANGED";
export const SCHEDULER_CONF_CHANGED = "SCHEDULER_CONF_CHANGED";
export const TECH_SEARCH_CHANGED = "TECH_SEARCH_CHANGED";
export const EXPAND_COLLAPSE_TREE = "EXPAND_COLLAPSE_TREE";
export const TECHNICIAN_WORKING_HOURS_CHANGED =
  "TECHNICIAN_WORKING_HOURS_CHANGED";

export const APPLY_USER_SETTINGS = "APPLY_USER_SETTINGS";
export const SAVE_USER_SETTINGS = "SAVE_USER_SETTINGS";
export const AUTO_SAVE_USER_SETTINGS = "AUTO_SAVE_USER_SETTINGS";
export const UPDATE_USER_SETTINGS = "UPDATE_USER_SETTINGS";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_GRID_STATE = "UPDATE_GRID_STATE";
export const UPDATE_APP_STATUS = "UPDATE_APP_STATUS";
export const PERFORM_ADV_TECH_SEARCH = "PERFORM_ADV_TECH_SEARCH";
export const APPLY_ADV_TECH_SEARCH = "APPLY_ADV_TECH_SEARCH";
export const REMOVE_ATS_RESULTS = "REMOVE_ATS_RESULTS";
export const FILTER_WORKORDER_TECHNICIANS = "FILTER_WORKORDER_TECHNICIANS";
export const FILTER_WORKORDER_EVENTS = "FILTER_WORKORDER_EVENTS";
export const SCHEDULE_MULTIPLE_EVENTS = "SCHEDULE_MULTIPLE_EVENTS";
export const ADD_REMOVE_TECHNICIAN_COLUMNS = "ADD_REMOVE_TECHNICIAN_COLUMNS";
export const CHANGE_TEAM_TERRITORY_SEQUENCE = "CHANGE_TEAM_TERRITORY_SEQUENCE";

export const UNASSIGN_WO = "UNASSIGN_WO";
export const WO_UNASSIGN_NO = "WO_UNASSIGN_NO";
export const RESET_USER_SETTINGS = "RESET_USER_SETTINGS";
export const DELETE_EVENTS = "DELETE_EVENTS";
export const DELETE_JDM_EVENTS = "DELETE_JDM_EVENTS";
export const REMOVE_WORKORDER = "REMOVE_WORKORDER";
export const SERACH_MMA_TECHNICIAN = "SERACH_MMA_TECHNICIAN";

// Actions
export const GET_APP_SETTINGS_ACTION = {
  key: KEY_APP_SETTINGS,
  type: GET_APP_SETTINGS
};
export const GET_WORKORDERS_ACTION = {
  key: KEY_WORKORDERS,
  type: GET_WORKORDERS
};
export const GET_VIEW_DEFINITION_ACTION = {
  key: KEY_VIEW_DEFINITION,
  type: GET_VIEW_DEFINITION
};
export const GET_TECHNICIAN_ACTION = {
  key: KEY_TECHNICIANS,
  type: GET_TECHNICIANS
};
export const GET_METADATA_ACTION = { key: KEY_METADATA, type: GET_METADATA };
export const GET_EVENTS_ACTION = { key: KEY_EVENTS, type: GET_EVENTS };
export const GET_TECH_SKILLS_ACTION = {
  key: KEY_TECH_SKILLS,
  type: GET_TECHNICIAN_SKILLS
};
export const GET_EVENT_HOVER_INFO_ACTION = {
  key: KEY_EVENTS_HOVER,
  type: GET_EVENT_HOVER_RULES
};

// Request State - Requested
export const APP_METADATA_REQUESTED = "APP_METADATA_REQUESTED";
export const DELETE_EVENT_REQUESTED = "DELETE_EVENT_REQUESTED";
export const ASSIGN_TO_TREE_REQUESTED = "ASSIGN_TO_TREE_REQUESTED";
export const UNASSIGN_WORKORDER_REQUESTED = "UNASSIGN_WORKORDER_REQUESTED";
export const METADATA_REQUESTED = "METADATA_REQUESTED";
export const WORKORDERS_REQUESTED = "WORKORDERS_REQUESTED";
export const DISPLAY_TAGS_REQUESTED = "DISPLAY_TAGS_REQUESTED";
export const APP_SETTINGS_REQUESTED = "APP_SETTINGS_REQUESTED";
export const USER_SETTINGS_REQUESTED = "USER_SETTINGS_REQUESTED";
export const SAVING_USER_SETTINGS = "SAVING_USER_SETTINGS";
export const WORKORDER_FIELD_LIST_REQUESTED = "WORKORDER_FIELD_LIST_REQUESTED";
export const VIEW_WORKORDER_COUNT_REQUESTED = "VIEW_WORKORDER_COUNT_REQUESTED";
export const VIEW_DEFINITION_REQUESTED = "VIEW_DEFINITION_REQUESTED";
export const MAP_VIEW_DATA_REQUESTED = "MAP_VIEW_DATA_REQUESTED";
export const TECHNICIANS_REQUESTED = "TECHNICIANS_REQUESTED";
export const TECHNICIANS_DETAILS_REQUESTED = "TECHNICIANS_DETAILS_REQUESTED";
export const TECHNICIANS_WORKING_HOURS_REQUESTED =
  "TECHNICIANS_WORKING_HOURS_REQUESTED";
export const TECHNICIANS_METADATA_REQUESTED = "TECHNICIANS METADATA REQUESTED";
export const TEAM_METADATA_REQUESTED = "TEAM METADATA REQUESTED";
export const EVENTS_METADATA_REQUESTED = "EVENTS METADATA REQUESTED";
export const EVENT_SUBJECT_REQUESTED = "EVENT_SUBJECT_REQUESTED";
export const EVENTS_REQUESTED = "EVENTS_REQUESTED";
export const EVENTS_HOVER_REQUESTED = "EVENTS_HOVER_REQUESTED";
export const WO_MATCH_TECH_SKILLS_REQUESTED = "WO_MATCH_TECH_SKILLS_REQUESTED";
export const CREAT_EVENT_REQUESTED = "CREAT_EVENT_REQUESTED";
export const UPDATE_EVENT_REQUESTED = "UPDATE_EVENT_REQUESTED";
export const SEARCH_TECHNICIANS_REQUESTED = "SEARCH_TECHNICIANS_REQUESTED";
export const INLINE_TECHNICIAN_SEARCH_REQUESTED =
  "INLINE_TECHNICIAN_SEARCH_REQUESTED";
export const ADV_TECH_SEARCH_REQUESTED = "ADV_TECH_SEARCH_REQUESTED";
export const ADV_TECH_SEARCH_NO_WORKORDER_SELECTION =
  "ADV_TECH_SEARCH_NO_WORKORDER_SELECTION";
export const DELTA_WORK_ORDER_REQUESTED = "DELTA_WORK_ORDER_REQUESTED";
export const FILTER_TECHNICIAN_REQUESTED = "FILTER_TECHNICIAN_REQUESTED";
export const DISPATCHER_LIST_REQUESTED = "DISPATCHER_LIST_REQUESTED";
export const POST_USER_SETTINGS_REQUESTED = "POST_USER_SETTINGS_REQUESTED";
export const WORKORDER_EVENTS_REQUESTED = "WORKORDER_EVENTS_REQUESTED";
export const MULTIASSIGN_EVENTS_REQUESTED = "MULTIASSIGN_EVENTS_REQUESTED";
export const EVENT_BUSINESS_HOUR_REQUESTED = "EVENT_BUSINESS_HOUR_REQUESTED";
export const GET_EVENT_IDS_REQUESTED = "GET_EVENT_IDS_REQUESTED";
export const LOAD_EVENT_IDS_REQUESTED = "LOAD_EVENT_IDS_REQUESTED";

// Request State - Loaded
export const METADATA_LOADED = "METADATA_LOADED";
export const WORKORDERS_LOADED = "WORKORDERS_LOADED";
export const DISPLAY_TAGS_LOADED = "DISPLAY_TAGS_LOADED";
export const VIEWS_LOADED = "VIEWS_LOADED";
export const LOCALE_LOADED = "LOCALE_LOADED";
export const TIMEZONE_UPDATED = "TIMEZONE_UPDATED";
export const APP_SETTINGS_LOADED = "APP_SETTINGS_LOADED";
export const USER_SETTINGS_LOADED = "USER_SETTINGS_LOADED";
export const WORKORDER_FIELD_LIST_LOADED = "WORKORDER_FIELD_LIST_LOADED";
export const VIEW_WORKORDER_COUNT_LOADED = "VIEW_WORKORDER_COUNT_LOADED";
export const VIEW_DEFINITION_LOADED = "VIEW_DEFINITIONT_LOADED";
export const MAP_VIEW_DATA_LOADED = "MAP_VIEW_DATA_LOADED";
export const TECHNICIANS_LOADED = "TECHNICIANS_LOADED";
export const UPDATE_TECHNICIAN_DETAILS = "UPDATE_TECHNICIAN_DETAILS";
export const TECHNICIANS_WORKING_HOURS_LOADED =
  "TECHNICIANS_WORKING_HOURS_LOADED";
export const TECHNICIANS_METADATA_LOADED = "TECHNICIANS METADATA LOADED";
export const TEAM_METADATA_LOADED = "TEAM METADATA LOADED";
export const DELETE_EVENT_COMPLETED = " DELETE_EVENT_COMPLETED";
export const ASSIGN_TO_TREE_COMPLETED = " ASSIGN_TO_TREE_COMPLETED";
export const UNASSIGN_WORKORDER_COMPLETED = " UNASSIGN_WORKORDER_COMPLETED";
export const EVENT_DELETE_COMPLETED = "EVENT_DELETE_COMPLETED";
export const EVENTS_METADATA_LOADED = "EVENTS METADATA LOADED";
export const EVENT_SUBJECT_LOADED = "EVENT_SUBJECT_LOADED";
export const EVENTS_LOADED = "EVENTS_LOADED";
export const EVENTS_LOADING_STARTED = "EVENTS_LOADING_STARTED";
export const EVENTS_LOADING_IN_PROGRESS = "EVENTS_LOADING_IN_PROGRESS";
export const EVENTS_LOADING_COMPLETE = "EVENTS_LOADING_COMPLETE";
export const EVENT_SAVING_COMPLETE = "EVENT_SAVING_COMPLETE";
export const EVENTS_LOADING_ERRORED = "EVENTS_LOADING_ERRORED";
export const EVENTS_HOVER_LOADED = "EVENTS_HOVER_LOADED";
export const TIMEZONE_LOADED = "TIMEZONE_LOADED";
export const TECHNICIAN_SKILLS_LOADED = "TECHNICIAN_SKILLS_LOADED";
export const WO_MATCH_TECH_SKILLS_LOADED = "WO_MATCH_TECH_SKILLS_LOADED";
export const SEARCH_TECHNICIANS_LOADED = "SEARCH_TECHNICIANS_LOADED";
export const ADV_TECH_SEARCH_LOADED = "ADV_TECH_SEARCH_LOADED";
export const DELTA_WORK_ORDER_LOADED = "DELTA_WORK_ORDER_LOADED";
export const FILTER_TECHNICIAN_LOADED = "FILTER_TECHNICIAN_LOADED";
export const DISPATCHER_LIST_LOADED = "DISPATCHER_LIST_LOADED";
export const POST_USER_SETTINGS_LOADED = "POST_USER_SETTINGS_LOADED";
export const WORKORDER_EVENTS_LOADED = "WORKORDER_EVENTS_LOADED";
export const REMOVE_WORKORDER_EVENTS = "REMOVE_WORKORDER_EVENTS";
export const MULTIASSIGN_EVENTS_COMPLETED = "MULTIASSIGN_EVENTS_COMPLETED";
export const MULTIASSIGN_EVENTS_UPDATED = "MULTIASSIGN_EVENTS_UPDATED";
export const EXPAND_TEAM_AFTER_EVENT_REFRESH =
  "EXPAND_TEAM_AFTER_EVENT_REFRESH";
export const EVENT_BUSINESS_HOUR_LOADED = "EVENT_BUSINESS_HOUR_LOADED";
export const GET_EVENT_IDS_LOADED = "GET_EVENT_IDS_LOADED";
export const LOAD_EVENT_IDS_COMPLETE = "LOAD_EVENT_IDS_COMPLETE";
export const LOAD_WIDE_RANGE_EVENTS_COMPLETE =
  "LOAD_WIDE_RANGE_EVENTS_COMPLETE";

// Request State - API Error
export const WORKORDERS_API_ERRORED = "WORKORDERS_API_ERRORED";
export const DATE_SELECTION_ERRORED = "DATE_SELECTION_ERRORED";
export const DISPLAY_TAGS_API_ERRORED = "DISPLAY_TAGS_API_ERRORED";
export const APP_SETTINGS_API_ERRORED = "APP_SETTINGS_API_ERRORED";
export const USER_SETTINGS_API_ERRORED = "USER_SETTINGS_API_ERRORED";
export const SAVING_USER_SETTINGS_API_ERRORED =
  "SAVING_USER_SETTINGS_API_ERRORED";
export const WORKORDER_FIELD_LIST_API_ERRORED =
  "WORKORDER_FIELD_LIST_API_ERRORED";
export const VIEW_WORKORDER_COUNT_API_ERRORED =
  "VIEW_WORKORDER_COUNT_API_ERRORED";
export const VIEW_DEFINITION_API_ERRORED = "VIEW_DEFINITION_API_ERRORED";
export const MAP_VIEW_DATA_API_ERRORED = "MAP_VIEW_DATA_API_ERRORED";
export const TECHNICIANS_API_ERRORED = "TECHNICIANS_API_ERRORED";
export const TECHNICIANS_DETAILS_API_ERRORED =
  "TECHNICIANS_DETAILS_API_ERRORED";
export const TECHNICIANS_WORKING_HOURS_API_ERRORED =
  "TECHNICIANS_WORKING_HOURS_API_ERRORED";
export const TECHNICIANS_METADATA_API_ERRORED =
  "TECHNICIANS METADATA API ERRORED";
export const TEAM_METADATA_API_ERRORED = "TEAM METADATA API ERRORED";
export const EVENTS_METADATA_API_ERRORED = "EVENTS METADATA API ERRORED";
export const EVENT_SUBJECT_ERRORED = "EVENT_SUBJECT_ERRORED";
export const EVENTS_API_ERRORED = "EVENTS_API_ERRORED";
export const DELETE_EVENT_ERRORED = "DELETE_EVENT_ERRORED";
export const EVENTS_HOVER_API_ERRORED = "EVENTS_HOVER_API_ERRORED";
export const METADATA_API_ERRORED = "METADATA_API_ERRORED";
export const WO_MATCH_TECH_SKILLS_API_ERRORED =
  "WO_MATCH_TECH_SKILLS_API_ERRORED";
export const SEARCH_TECHNICIANS_ERRORED = "SEARCH_TECHNICIANS_ERRORED";
export const CREAT_EVENT_ERROR = "CREAT_EVENT_ERROR";
export const UPDATE_EVENT_ERROR = "UPDATE_EVENT_ERROR";
export const ADV_TECH_SEARCH_ERRORED = "ADV_TECH_SEARCH_ERRORED";
export const DELTA_WORK_ORDER_ERROR = "DELTA_WORK_ORDER_ERROR";
export const FILTER_TECHNICIAN_ERRORED = "FILTER_TECHNICIAN_ERRORED";
export const DISPATCHER_LIST_ERRORED = "DISPATCHER_LIST_ERRORED";
export const POST_USER_SETTINGS_ERRORED = "POST_USER_SETTINGS_ERRORED";
export const WORKORDER_EVENTS_ERRORED = "WORKORDER_EVENTS_ERRORED";
export const MULTIASSIGN_EVENTS_ERRORED = "MULTIASSIGN_EVENTS_ERRORED";
export const TECHNICIAN_SCHEDULING_ERROR = "TECHNICIAN_SCHEDULING_ERROR";
export const MAP_TECHWO_LOCATION_ERROR = "MAP_TECHWO_LOCATION_ERROR";
export const EVENT_BUSINESS_HOUR_ERRORED = "EVENT_BUSINESS_HOUR_ERRORED";
export const ASSIGN_TO_TREE_ERRORED = "ASSIGN_TO_TREE_ERRORED";
export const UNASSIGN_WORKORDER_ERRORED = "UNASSIGN_WORKORDER_ERRORED";
export const EVENT_DELETE_ERRORED = "EVENT_DELETE_ERRORED";
export const RESET_USER_SETTINGS_ERRORED = "RESET_USER_SETTINGS_ERRORED";

export const GET_EVENT_IDS_ERRORED = "GET_EVENT_IDS_ERRORED";
export const LOAD_EVENT_IDS_ERRORED = "LOAD_EVENT_IDS_ERRORED";
export const LOAD_WIDE_RANGE_EVENTS_ERRORED = "LOAD_WIDE_RANGE_EVENTS_ERRORED";

export const FILTERING_EVENTS_FAILED = "FILTERING_EVENTS_FAILED";
export const FILTERING_EVENTS_STARTED = "FILTERING_EVENTS_STARTED";
export const FILTERING_EVENTS_ERRORED = "FILTERING_EVENTS_ERRORED";

export const FILTERING_TECHNICIANS_FAILED = "FILTERING_TECHNICIANS_FAILED";
export const FILTERING_TECHNICIANS_STARTED = "FILTERING_TECHNICIANS_STARTED";

export const GET_APP_METADATA = "GET_APP_METADATA";
export const MAP_VIEW_DATA_CLEAR = "MAP_VIEW_DATA_CLEAR";
export const MAP_VIEW_DATA_CLEARED = "MAP_VIEW_DATA_CLEARED";
export const STATUS_DATA_CLEAR = "STATUS_DATA_CLEAR";
export const SEARCH_TEXT_EMPTY = "SEARCH_TEXT_EMPTY";
export const SEARCH_TECH_DATA_CLEAR = "SEARCH_TECH_DATA_CLEAR";
export const SEARCH_TECH_DATA_CLEARED = "SEARCH_TECH_DATA_CLEARED";
export const ADV_TECH_SEARCH_CLEARED = "ADV_TECH_SEARCH_CLEARED";
export const RESET_SCHEDULER_VIEW = "RESET_SCHEDULER_VIEW";
export const SEARCH_KEY_MATCH_EMPTY = "SEARCH_KEYMATCH_EMPTY";
export const SEARCH_TECH_DATA_EMPTY = "SEARCH_TECH_DATA_EMPTY";
export const SHOW_ROUTE_TECH_DATA_EMPTY = "SHOW_ROUTE_TECH_DATA_EMPTY";

// Scheduler state change Action types
export const UPDATE_SCHEDULER_STATE = "UPDATE_SCHEDULER_STATE";
export const START_END_DATE_CHANGED = "START_END_DATE_CHANGED";
export const ZOOM_OUT_MAX_REACHED = "ZOOM_OUT_MAX_REACHED";
export const ZOOM_IN_MAX_REACHED = "ZOOM_IN_MAX_REACHED";

export const USER_SESSION_EXPIRED = "USER_SESSION_EXPIRED";
export const INPUT_TEXT_ERROR = "INPUT_TEXT_ERROR";
