/**
 * The TOOL_SeedStandardSFM class will get json files from static resource
 * and perform insert/update of SFM components.
 *
 * @author D B Sathish Kumar
 * @version 20.2
 * @created 27/Aug/2020
 * @updated 27/Aug/2020
 */

global without sharing class TOOL_SeedStandardSFM {

    @future(callout=true)
    public static void installSFM(String key, String emailId, boolean isManual, String installerId) {
        
    }

}