import {
  ASSIGN_TO_TREE_REQUESTED,
  ASSIGN_TO_TREE_COMPLETED,
  DATE_SELECTION_ERRORED,
  EXPAND_TEAM_AFTER_EVENT_REFRESH,
  EVENTS_LOADING_STARTED,
  EVENTS_LOADING_IN_PROGRESS,
  EVENTS_LOADING_COMPLETE,
  EVENTS_LOADING_ERRORED,
  DELETE_EVENT_REQUESTED,
  WORKORDERS_REQUESTED,
  WORKORDERS_LOADED,
  INPUT_TEXT_ERROR,
  WORKORDERS_API_ERRORED,
  USER_SETTINGS_LOADED,
  SAVING_USER_SETTINGS_API_ERRORED,
  SEARCH_TEXT_EMPTY,
  SEARCH_KEY_MATCH_EMPTY,
  SEARCH_TECHNICIANS_ERRORED,
  SEARCH_TECH_DATA_EMPTY,
  ADV_TECH_SEARCH_NO_WORKORDER_SELECTION,
  ADV_TECH_SEARCH_REQUESTED,
  ADV_TECH_SEARCH_LOADED,
  ADV_TECH_SEARCH_ERRORED,
  SHOW_ROUTE_TECH_DATA_EMPTY,
  POST_USER_SETTINGS_LOADED,
  TECHNICIAN_SCHEDULING_ERROR,
  MAP_TECHWO_LOCATION_ERROR,
  SEARCH_TECHNICIANS_REQUESTED,
  RESET_SCHEDULER_VIEW,
  SEARCH_TECHNICIANS_LOADED,
  FILTERING_EVENTS_FAILED,
  FILTERING_EVENTS_STARTED,
  FILTERING_EVENTS_ERRORED,
  FILTERING_TECHNICIANS_FAILED,
  FILTERING_TECHNICIANS_STARTED,
  FILTER_TECHNICIAN_ERRORED,
  CREAT_EVENT_ERROR,
  EVENT_SAVING_COMPLETE,
  ZOOM_OUT_MAX_REACHED,
  ZOOM_IN_MAX_REACHED,
  WORKORDER_EVENTS_ERRORED,
  USER_SESSION_EXPIRED,
  STATUS_DATA_CLEAR,
  WO_MATCH_TECH_SKILLS_API_ERRORED,
  MULTIASSIGN_EVENTS_ERRORED,
  ASSIGN_TO_TREE_ERRORED,
  UNASSIGN_WORKORDER_ERRORED,
  UNASSIGN_WORKORDER_COMPLETED,
  DELETE_EVENT_ERRORED,
  UPDATE_EVENT_ERROR,
  DELETE_EVENT_COMPLETED,
  RESET_USER_SETTINGS_ERRORED,
  EVENT_BUSINESS_HOUR_ERRORED,
  EVENT_SUBJECT_ERRORED,
  UNASSIGN_WORKORDER_REQUESTED,
  MAP_VIEW_DATA_API_ERRORED,
  VIEW_DEFINITION_API_ERRORED
} from "constants/ActionConstants";
import {
  EVENTSTAG154,
  TAG030,
  TAG033,
  TAG096,
  TAG099,
  TAG102,
  TAG103,
  TAG104,
  TAG105,
  TAG106,
  TAG107,
  TAG111,
  TAG112,
  TAG114,
  TAG115,
  TAG117,
  TAG138,
  TAG139,
  TAG140,
  TAG141,
  TAG142,
  TAG152,
  TAG156,
  TAG157,
  TAG165,
  TAG166,
  TAG167,
  TAG175,
  TAG176,
  TAG199,
  TAG205,
  TAG212,
  TAG222,
  TAG243,
  TAG245,
  TAG310,
  TAG380,
  TAG381,
  TAG382,
  TAG506,
  TAG507,
  TAG508,
  TAG509,
  TAG510,
  TAG511
} from "constants/DisplayTagConstants";
import {
  ERROR_TYPE,
  INFO_TYPE,
  WARNING_TYPE,
  PROGRESS_TYPE,
  CLEAR_TYPE
} from "constants/AppConstants";
import { getDisplayValue } from "utils/DCUtils";

const ACTION_TO_DISPLAYTAG_MAPPING = {
  [ADV_TECH_SEARCH_ERRORED]: TAG380,
  [ADV_TECH_SEARCH_LOADED]: TAG381,
  [ADV_TECH_SEARCH_NO_WORKORDER_SELECTION]: TAG382,
  [ADV_TECH_SEARCH_REQUESTED]: TAG381,

  [ASSIGN_TO_TREE_COMPLETED]: TAG205,
  [ASSIGN_TO_TREE_ERRORED]: TAG117,
  [ASSIGN_TO_TREE_REQUESTED]: TAG096,

  [DATE_SELECTION_ERRORED]: TAG102,
  [DELETE_EVENT_ERRORED]: TAG114,

  [EVENT_BUSINESS_HOUR_ERRORED]: TAG222,
  [EVENT_SAVING_COMPLETE]: TAG099,
  [EVENTS_LOADING_COMPLETE]: TAG103,
  [EVENTS_LOADING_ERRORED]: TAG104,
  [EVENTS_LOADING_STARTED]: TAG033,
  [EVENT_SUBJECT_ERRORED]: TAG212,
  [USER_SESSION_EXPIRED]: TAG243,

  [DELETE_EVENT_COMPLETED]: TAG176,

  [EXPAND_TEAM_AFTER_EVENT_REFRESH]: EVENTSTAG154,

  [FILTERING_EVENTS_FAILED]: TAG506,
  [FILTERING_EVENTS_STARTED]: TAG507,
  [FILTERING_TECHNICIANS_FAILED]: TAG508,
  [FILTERING_TECHNICIANS_STARTED]: TAG509,

  [MULTIASSIGN_EVENTS_ERRORED]: TAG112,

  [POST_USER_SETTINGS_LOADED]: TAG310,
  [RESET_SCHEDULER_VIEW]: TAG152,
  [RESET_USER_SETTINGS_ERRORED]: TAG165,
  [SAVING_USER_SETTINGS_API_ERRORED]: TAG142,

  [SEARCH_KEY_MATCH_EMPTY]: TAG107,
  [SEARCH_TECH_DATA_EMPTY]: TAG105,
  [SEARCH_TECHNICIANS_ERRORED]: TAG140,
  [SEARCH_TECHNICIANS_LOADED]: TAG103,
  [SEARCH_TECHNICIANS_REQUESTED]: TAG245,
  [SEARCH_TEXT_EMPTY]: TAG106,
  [SHOW_ROUTE_TECH_DATA_EMPTY]: TAG166,

  [TECHNICIAN_SCHEDULING_ERROR]: TAG199,

  [USER_SETTINGS_LOADED]: TAG141,
  [UPDATE_EVENT_ERROR]: TAG115,
  [UNASSIGN_WORKORDER_COMPLETED]: TAG175,
  [UNASSIGN_WORKORDER_REQUESTED]: TAG096,

  [WORKORDERS_API_ERRORED]: TAG139,
  [WORKORDERS_LOADED]: TAG138,
  [WORKORDERS_REQUESTED]: TAG030,

  [ZOOM_OUT_MAX_REACHED]: TAG510,
  [ZOOM_IN_MAX_REACHED]: TAG511
};

export function appStatusAction(type, message, msgType, data) {
  const action = {
    message,
    msgType,
    type
  };
  if (msgType === ERROR_TYPE) {
    action.data = data || {
      error: {
        message: getDisplayValue(getDisplayMessage(type, message)),
        errorCode: "Type Error"
      }
    };
  }
  return action;
}

const getDisplayMessage = (type, message) =>
  message || ACTION_TO_DISPLAYTAG_MAPPING[type];

export function reducer(state = null, action) {
  const { data, message, msgType = INFO_TYPE, type } = action;
  const displayMsg = getDisplayMessage(type, message);
  switch (type) {
    case ADV_TECH_SEARCH_ERRORED:
    case CREAT_EVENT_ERROR:
    case UPDATE_EVENT_ERROR:
    case EVENTS_LOADING_ERRORED:
    case FILTERING_EVENTS_FAILED:
    case FILTERING_EVENTS_ERRORED:
    case FILTERING_TECHNICIANS_FAILED:
    case FILTER_TECHNICIAN_ERRORED:
    case MAP_TECHWO_LOCATION_ERROR:
    case SAVING_USER_SETTINGS_API_ERRORED:
    case SEARCH_TECHNICIANS_ERRORED:
    case USER_SESSION_EXPIRED:
    case WORKORDERS_API_ERRORED:
    case WORKORDER_EVENTS_ERRORED:
    case MULTIASSIGN_EVENTS_ERRORED:
    case ASSIGN_TO_TREE_ERRORED:
    case UNASSIGN_WORKORDER_ERRORED:
    case EVENT_SUBJECT_ERRORED:
    case MAP_VIEW_DATA_API_ERRORED:
    case VIEW_DEFINITION_API_ERRORED:
    case DELETE_EVENT_ERRORED:
    case WO_MATCH_TECH_SKILLS_API_ERRORED:
      return {
        ...state,
        data,
        message: displayMsg,
        msgType: ERROR_TYPE,
        type
      };

    case ADV_TECH_SEARCH_NO_WORKORDER_SELECTION:
    case TECHNICIAN_SCHEDULING_ERROR:
    case DATE_SELECTION_ERRORED:
    case INPUT_TEXT_ERROR:
      return { ...state, message: displayMsg, msgType: WARNING_TYPE };

    case STATUS_DATA_CLEAR:
      return { ...state, message: displayMsg, msgType: CLEAR_TYPE };

    case ADV_TECH_SEARCH_LOADED:
    case EVENT_SAVING_COMPLETE:
    case EVENTS_LOADING_COMPLETE:
    case EXPAND_TEAM_AFTER_EVENT_REFRESH:
    case DELETE_EVENT_COMPLETED:
    case POST_USER_SETTINGS_LOADED:
    case RESET_SCHEDULER_VIEW:
    case ZOOM_OUT_MAX_REACHED:
    case ZOOM_IN_MAX_REACHED:
    case SEARCH_TECH_DATA_EMPTY:
    case SEARCH_KEY_MATCH_EMPTY:
    case SEARCH_TEXT_EMPTY:
    case SEARCH_TECHNICIANS_LOADED:
    case SHOW_ROUTE_TECH_DATA_EMPTY:
    case USER_SETTINGS_LOADED:
    case WORKORDERS_LOADED:
    case ASSIGN_TO_TREE_COMPLETED:
    case UNASSIGN_WORKORDER_COMPLETED:
      return { ...state, message: displayMsg, msgType };

    case ADV_TECH_SEARCH_REQUESTED:
    case EVENTS_LOADING_STARTED:
    case EVENTS_LOADING_IN_PROGRESS:
    case FILTERING_EVENTS_STARTED:
    case FILTERING_TECHNICIANS_STARTED:
    case SEARCH_TECHNICIANS_REQUESTED:
    case WORKORDERS_REQUESTED:
    case DELETE_EVENT_REQUESTED:
    case ASSIGN_TO_TREE_REQUESTED:
    case UNASSIGN_WORKORDER_REQUESTED:
      return { ...state, message: displayMsg, msgType: PROGRESS_TYPE };
    default:
      return state;
  }
}
