public with sharing class Designer_TagsDefinition {

    public static void getSFMTags(Map<String,String> tags){
        tags.put('SFM001-TAG001', system.label.SFM001_TAG001);
        tags.put('SFM001-TAG002', system.label.SFM001_TAG002);
        tags.put('SFM001-TAG003', system.label.SFM001_TAG003);
        tags.put('SFM001-TAG004', system.label.SFM001_TAG004);
        tags.put('SFM001-TAG005', system.label.SFM001_TAG005);
        tags.put('SFM001-TAG006', system.label.SFM001_TAG006);
        tags.put('SFM001-TAG007', system.label.SFM001_TAG007);
        tags.put('SFM001-TAG008', system.label.SFM001_TAG008);
        tags.put('SFM001-TAG009', system.label.SFM001_TAG009);
        tags.put('SFM001-TAG010', system.label.SFM001_TAG010);
        tags.put('SFM001-TAG011', system.label.SFM001_TAG011);
        tags.put('SFM001-TAG012', system.label.SFM001_TAG012);
        tags.put('SFM001-TAG013', system.label.SFM001_TAG013);
        tags.put('SFM001-TAG014', system.label.SFM001_TAG014);
        tags.put('SFM001-TAG015', system.label.SFM001_TAG015);
        tags.put('SFM001-TAG016', system.label.SFM001_TAG016);
        tags.put('SFM001-TAG017', system.label.SFM001_TAG017);
        tags.put('SFM001-TAG018', system.label.SFM001_TAG018);
        tags.put('SFM001-TAG019', system.label.SFM001_TAG019);
        tags.put('SFM001-TAG020', system.label.SFM001_TAG020);
        tags.put('SFM001-TAG021', system.label.SFM001_TAG021);
        tags.put('SFM001-TAG022', system.label.SFM001_TAG022);
        tags.put('SFM001-TAG023', system.label.SFM001_TAG023);
        tags.put('SFM001-TAG024', system.label.SFM001_TAG024);
        tags.put('SFM001-TAG025', system.label.SFM001_TAG025);
        tags.put('SFM001-TAG026', system.label.SFM001_TAG026);
        tags.put('SFM001-TAG027', system.label.SFM001_TAG027);
        tags.put('SFM001-TAG028', system.label.SFM001_TAG028);
        tags.put('SFM001-TAG029', system.label.SFM001_TAG029);
        tags.put('SFM001-TAG030', system.label.SFM001_TAG030);
        tags.put('SFM001-TAG031', system.label.SFM001_TAG031);
        tags.put('SFM001-TAG032', system.label.SFM001_TAG032);
        tags.put('SFM001-TAG033', system.label.SFM001_TAG033);
        tags.put('SFM001-TAG034', system.label.SFM001_TAG034);
        tags.put('SFM001-TAG035', system.label.SFM001_TAG035);
        tags.put('SFM001-TAG036', system.label.SFM001_TAG036);
        tags.put('SFM001-TAG037', system.label.SFM001_TAG037);
        tags.put('SFM001-TAG038', system.label.SFM001_TAG038);
        tags.put('SFM001-TAG039', system.label.SFM001_TAG039);
        tags.put('SFM001-TAG040', system.label.SFM001_TAG040);
        tags.put('SFM001-TAG041', system.label.SFM001_TAG041);
        tags.put('SFM001-TAG042', system.label.SFM001_TAG042);
        tags.put('SFM001-TAG043', system.label.SFM001_TAG043);
        tags.put('SFM001-TAG044', system.label.SFM001_TAG044);
        tags.put('SFM001-TAG045', system.label.SFM001_TAG045);
        tags.put('SFM001-TAG046', system.label.SFM001_TAG046);
        tags.put('SFM001-TAG047', system.label.SFM001_TAG047);
        tags.put('SFM001-TAG048', system.label.SFM001_TAG048);
        tags.put('SFM001-TAG049', system.label.SFM001_TAG049);
        tags.put('SFM001-TAG050', system.label.SFM001_TAG050);
        tags.put('SFM001-TAG051', system.label.SFM001_TAG051);
        tags.put('SFM001-TAG052', system.label.SFM001_TAG052);
        tags.put('SFM001-TAG053', system.label.SFM001_TAG053);
        tags.put('SFM001-TAG054', system.label.SFM001_TAG054);
        tags.put('SFM001-TAG055', system.label.SFM001_TAG055);
        tags.put('SFM001-TAG056', system.label.SFM001_TAG056);
        tags.put('SFM001-TAG057', system.label.SFM001_TAG057);
        tags.put('SFM001-TAG058', system.label.SFM001_TAG058);
        tags.put('SFM001-TAG059', system.label.SFM001_TAG059);
        tags.put('SFM001-TAG060', system.label.SFM001_TAG060);
        tags.put('SFM001-TAG061', system.label.SFM001_TAG061);
        tags.put('SFM001-TAG062', system.label.SFM001_TAG062);
        tags.put('SFM001-TAG063', system.label.SFM001_TAG063);
        tags.put('SFM001-TAG064', system.label.SFM001_TAG064);
        tags.put('SFM001-TAG065', system.label.SFM001_TAG065);
        tags.put('SFM001-TAG066', system.label.SFM001_TAG066);
        tags.put('SFM001-TAG067', system.label.SFM001_TAG067);
        tags.put('SFM001-TAG068', system.label.SFM001_TAG068);
        tags.put('SFM001-TAG069', system.label.SFM001_TAG069);
        tags.put('SFM001-TAG070', system.label.SFM001_TAG070);
        tags.put('SFM001-TAG071', system.label.SFM001_TAG071);
        tags.put('SFM001-TAG072', system.label.SFM001_TAG072);
        tags.put('SFM001-TAG073', system.label.SFM001_TAG073);
        tags.put('SFM001-TAG074', system.label.SFM001_TAG074);
        tags.put('SFM001-TAG075', system.label.SFM001_TAG075);
        tags.put('SFM001-TAG076', system.label.SFM001_TAG076);
        tags.put('SFM001-TAG077', system.label.SFM001_TAG077);
        tags.put('SFM001-TAG078', system.label.SFM001_TAG078);
        tags.put('SFM001-TAG079', system.label.SFM001_TAG079);
        tags.put('SFM001-TAG080', system.label.SFM001_TAG080);
        tags.put('SFM001-TAG081', system.label.SFM001_TAG081);
        tags.put('SFM001-TAG082', system.label.SFM001_TAG082);
        tags.put('SFM001-TAG083', system.label.SFM001_TAG083);
        tags.put('SFM001-TAG084', system.label.SFM001_TAG084);
        tags.put('SFM001-TAG085', system.label.SFM001_TAG085);
        tags.put('SFM001-TAG086', system.label.SFM001_TAG086);
        tags.put('SFM001-TAG087', system.label.SFM001_TAG087);
        tags.put('SFM001-TAG088', system.label.SFM001_TAG088);
        tags.put('SFM001-TAG089', system.label.SFM001_TAG089);
        tags.put('SFM001-TAG090', system.label.SFM001_TAG090);
        tags.put('SFM001-TAG091', system.label.SFM001_TAG091);
        tags.put('SFM001-TAG092', system.label.SFM001_TAG092);
        tags.put('SFM001-TAG093', system.label.SFM001_TAG093);
        tags.put('SFM001-TAG094', system.label.SFM001_TAG094);
        tags.put('SFM001-TAG095', system.label.SFM001_TAG095);
        tags.put('SFM001-TAG096', system.label.SFM001_TAG096);
        tags.put('SFM001-TAG097', system.label.SFM001_TAG097);
        tags.put('SFM001-TAG098', system.label.SFM001_TAG098);
        tags.put('SFM001-TAG099', system.label.SFM001_TAG099);
        tags.put('SFM001-TAG100', system.label.SFM001_TAG100);
        tags.put('SFM001-TAG101', system.label.SFM001_TAG101);
        tags.put('SFM001-TAG102', system.label.SFM001_TAG102);
        tags.put('SFM001-TAG103', system.label.SFM001_TAG103);
        tags.put('SFM001-TAG104', system.label.SFM001_TAG104);
        tags.put('SFM001-TAG105', system.label.SFM001_TAG105);
        tags.put('SFM001-TAG106', system.label.SFM001_TAG106);
        tags.put('SFM001-TAG107', system.label.SFM001_TAG107);
        tags.put('SFM001-TAG108', system.label.SFM001_TAG108);
        tags.put('SFM001-TAG109', system.label.SFM001_TAG109);
        tags.put('SFM001-TAG110', system.label.SFM001_TAG110);
        tags.put('SFM001-TAG111', system.label.SFM001_TAG111);
        tags.put('SFM001-TAG112', system.label.SFM001_TAG112);
        tags.put('SFM001-TAG113', system.label.SFM001_TAG113);
        tags.put('SFM001-TAG114', system.label.SFM001_TAG114);
        tags.put('SFM001-TAG115', system.label.SFM001_TAG115);
        tags.put('SFM001-TAG116', system.label.SFM001_TAG116);
        tags.put('SFM001-TAG117', system.label.SFM001_TAG117);
        tags.put('SFM001-TAG118', system.label.SFM001_TAG118);
        tags.put('SFM001-TAG119', system.label.SFM001_TAG119);
        tags.put('SFM001-TAG120', system.label.SFM001_TAG120);
        tags.put('SFM001-TAG121', system.label.SFM001_TAG121);
        tags.put('SFM001-TAG122', system.label.SFM001_TAG122);
        tags.put('SFM001-TAG123', system.label.SFM001_TAG123);
        tags.put('SFM001-TAG124', system.label.SFM001_TAG124);
        tags.put('SFM001-TAG125', system.label.SFM001_TAG125);
        tags.put('SFM001-TAG126', system.label.SFM001_TAG126);
        tags.put('SFM001-TAG127', system.label.SFM001_TAG127);
        tags.put('SFM001-TAG128', system.label.SFM001_TAG128);
        tags.put('SFM001-TAG129', system.label.SFM001_TAG129);
        tags.put('SFM001-TAG130', system.label.SFM001_TAG130);
        tags.put('SFM001-TAG131', system.label.SFM001_TAG131);
        tags.put('SFM001-TAG132', system.label.SFM001_TAG132);
        tags.put('SFM001-TAG133', system.label.SFM001_TAG133);
        tags.put('SFM001-TAG134', system.label.SFM001_TAG134);
        tags.put('SFM001-TAG135', system.label.SFM001_TAG135);
        tags.put('SFM001-TAG136', system.label.SFM001_TAG136);
        tags.put('SFM001-TAG137', system.label.SFM001_TAG137);
        tags.put('SFM001-TAG138', system.label.SFM001_TAG138);
        tags.put('SFM001-TAG139', system.label.SFM001_TAG139);
        tags.put('SFM001-TAG140', system.label.SFM001_TAG140);
        tags.put('SFM001-TAG141', system.label.SFM001_TAG141);
        tags.put('SFM001-TAG142', system.label.SFM001_TAG142);
        tags.put('SFM001-TAG143', system.label.SFM001_TAG143);
        tags.put('SFM001-TAG144', system.label.SFM001_TAG144);
        tags.put('SFM001-TAG145', system.label.SFM001_TAG145);
        tags.put('SFM001-TAG146', system.label.SFM001_TAG146);
        tags.put('SFM001-TAG147', system.label.SFM001_TAG147);
        tags.put('SFM001-TAG148', system.label.SFM001_TAG148);
        tags.put('SFM001-TAG149', system.label.SFM001_TAG149);
        tags.put('SFM001-TAG150', system.label.SFM001_TAG150);
        tags.put('SFM001-TAG151', system.label.SFM001_TAG151);
        tags.put('SFM001-TAG152', system.label.SFM001_TAG152);
        tags.put('SFM001-TAG153', system.label.SFM001_TAG153);
        tags.put('SFM001-TAG154', system.label.SFM001_TAG154);
        tags.put('SFM001-TAG155', system.label.SFM001_TAG155);
        tags.put('SFM001-TAG156', system.label.SFM001_TAG156);
        tags.put('SFM001-TAG157', system.label.SFM001_TAG157);
        tags.put('SFM001-TAG158', system.label.SFM001_TAG158);
        tags.put('SFM001-TAG159', system.label.SFM001_TAG159);
        tags.put('SFM001-TAG160', system.label.SFM001_TAG160);
        tags.put('SFM001-TAG161', system.label.SFM001_TAG161);
        tags.put('SFM001-TAG162', system.label.SFM001_TAG162);
        tags.put('SFM001-TAG163', system.label.SFM001_TAG163);
        tags.put('SFM001-TAG164', system.label.SFM001_TAG164);
        tags.put('SFM001-TAG165', system.label.SFM001_TAG165);
        tags.put('SFM001-TAG166', system.label.SFM001_TAG166);
        tags.put('SFM001-TAG167', system.label.SFM001_TAG167);
        tags.put('SFM001-TAG168', system.label.SFM001_TAG168);
        tags.put('SFM001-TAG169', system.label.SFM001_TAG169);
        tags.put('SFM001-TAG171', system.label.SFM001_TAG171);
        tags.put('SFM001-TAG172', system.label.SFM001_TAG172);
        tags.put('SFM001-TAG173', system.label.SFM001_TAG173);
        tags.put('SFM001-TAG174', system.label.SFM001_TAG174);
        tags.put('SFM001-TAG175', system.label.SFM001_TAG175);
        tags.put('SFM001-TAG176', system.label.SFM001_TAG176);
        tags.put('SFM001-TAG177', system.label.SFM001_TAG177);
        tags.put('SFM001-TAG178', system.label.SFM001_TAG178);
        tags.put('SFM001-TAG179', system.label.SFM001_TAG179);
        tags.put('SFM001-TAG180', system.label.SFM001_TAG180);
        tags.put('SFM001-TAG181', system.label.SFM001_TAG181);
        tags.put('SFM001-TAG182', system.label.SFM001_TAG182);
        tags.put('SFM001-TAG183', system.label.SFM001_TAG183);
        tags.put('SFM001-TAG184', system.label.SFM001_TAG184);
        tags.put('SFM001-TAG185', system.label.SFM001_TAG185);
        tags.put('SFM001-TAG186', system.label.SFM001_TAG186);
        tags.put('SFM001-TAG187', system.label.SFM001_TAG187);
        tags.put('SFM001-TAG188', system.label.SFM001_TAG188);
        tags.put('SFM001-TAG189', system.label.SFM001_TAG189);
        tags.put('SFM001-TAG190', system.label.SFM001_TAG190);
        tags.put('SFM001-TAG191', system.label.SFM001_TAG191);
        tags.put('SFM001-TAG192', system.label.SFM001_TAG192);
        tags.put('SFM001-TAG193', system.label.SFM001_TAG193);
        tags.put('SFM001-TAG194', system.label.SFM001_TAG194);
        tags.put('SFM001-TAG195', system.label.SFM001_TAG195);
        tags.put('SFM001-TAG196', system.label.SFM001_TAG196);
        tags.put('SFM001-TAG197', system.label.SFM001_TAG197);
        tags.put('SFM001-On_Load', system.label.SFM001_TAG198);
        tags.put('SFM001-Help_Text', system.label.SFM001_TAG199);
        tags.put('SFM001-Help_URL', system.label.SFM001_TAG200);
        tags.put('SFM001-Title', system.label.SFM001_TAG201);
        tags.put('SFM001-No_of_Columns', system.label.SFM001_TAG202);
        tags.put('SFM001-Allow_New', system.label.SFM001_TAG203);
        tags.put('SFM001-Allow_Delete', system.label.SFM001_TAG204);
        tags.put('SFM001-Allow_Zero_Lines', system.label.SFM001_TAG205);
        tags.put('SFM001-Allow_Multi_Add_Using', system.label.SFM001_TAG206);
        tags.put('SFM001-Required', system.label.SFM001_TAG207);
        tags.put('SFM001-Read_Only', system.label.SFM001_TAG208);
        tags.put('SFM001-On_Exit', system.label.SFM001_TAG209);
        tags.put('SFM001-On_Change', system.label.SFM001_TAG210);
        tags.put('SFM001-Context', system.label.SFM001_TAG211);
        tags.put('SFM001-Override_Context', system.label.SFM001_TAG212);
        tags.put('SFM001-Matching_Field', system.label.SFM001_TAG213);
        tags.put('SFM001-Event_Type', system.label.SFM001_TAG214);
        tags.put('SFM001-Open_In', system.label.SFM001_TAG215);
        tags.put('SFM001-No_of_Rows', system.label.SFM001_TAG216);
        tags.put('SFM001-On_Click', system.label.SFM001_TAG241);
        tags.put('SFM001-TAG217', system.label.SFM001_TAG217);
        tags.put('SFM001-TAG218', system.label.SFM001_TAG218);
        tags.put('SFM001-TAG219', system.label.SFM001_TAG219);
        tags.put('SFM001-TAG220', system.label.SFM001_TAG220);
        tags.put('SFM001-TAG221', system.label.SFM001_TAG221);
        tags.put('SFM001-iPad_Hide_Quick_Save_Button', system.label.SFM001_TAG222);
        tags.put('SFM001-TAG223', system.label.SFM001_TAG223);
        tags.put('SFM001-TAG224', system.label.SFM001_TAG224);
        tags.put('SFM001-TAG225', system.label.SFM001_TAG225);
        tags.put('SFM001-TAG226', system.label.SFM001_TAG226);
        tags.put('SFM001-TAG227', system.label.SFM001_TAG227);
        tags.put('SFM001-TAG228', system.label.SFM001_TAG228);
        tags.put('SFM001-TAG229', system.label.SFM001_TAG229);
        tags.put('SFM001-TAG230', system.label.SFM001_TAG230);
        tags.put('SFM001-TAG231', system.label.SFM001_TAG231);
        tags.put('SFM001-TAG232', system.label.SFM001_TAG232);
        tags.put('SFM001-TAG233', system.label.SFM001_TAG233);
        tags.put('SFM001-TAG234', system.label.SFM001_TAG234);
        tags.put('SFM001-TAG235', system.label.SFM001_TAG235);
        tags.put('SFM001-TAG236', system.label.SFM001_TAG236);
        tags.put('SFM001-TAG237', system.label.SFM001_TAG237);
        tags.put('SFM001-TAG238', system.label.SFM001_TAG238);
        tags.put('SFM001-TAG239', system.label.SFM001_TAG239);
        tags.put('SFM001-TAG240', system.label.SFM001_TAG240);
        tags.put('SFM001-TAG242', system.label.SFM001_TAG242);
        tags.put('SFM001-TAG243', system.label.SFM001_TAG243);
        tags.put('SFM001-TAG244', system.label.SFM001_TAG244);
        tags.put('SFM001-TAG245', system.label.SFM001_TAG245);
        tags.put('SFM001-TAG246', system.label.SFM001_TAG246);
        tags.put('SFM001-TAG247', system.label.SFM001_TAG247);
        tags.put('SFM001-TAG248', system.label.SFM001_TAG248);
        tags.put('SFM001-TAG249', system.label.SFM001_TAG249);
        tags.put('SFM001-TAG250', system.label.SFM001_TAG250);
        tags.put('SFM001-TAG251', system.label.SFM001_TAG251);
        tags.put('SFM001-TAG252', system.label.SFM001_TAG252);
        tags.put('SFM001-TAG253', system.label.SFM001_TAG253);
        tags.put('SFM001-TAG254', system.label.SFM001_TAG254);
        tags.put('SFM001-TAG255', system.label.SFM001_TAG255);
        tags.put('SFM001-TAG256', system.label.SFM001_TAG256);
        tags.put('SFM001-TAG257', system.label.SFM001_TAG257);
        tags.put('SFM001-TAG258', system.label.SFM001_TAG258);
        tags.put('SFM001-TAG259', system.label.SFM001_TAG259);
        tags.put('SFM001-TAG260', system.label.SFM001_TAG260);
        tags.put('SFM001-TAG261', system.label.SFM001_TAG261);
        tags.put('SFM001-TAG262', system.label.SFM001_TAG262);
        tags.put('SFM001-TAG263', system.label.SFM001_TAG263);
        //Tags related to the iPad
        tags.put('SFM001-TAG264', system.label.SFM001_TAG264);
        tags.put('SFM001-TAG265', system.label.SFM001_TAG265);
        tags.put('SFM001-iPad_Hide_Save_Button', system.label.SFM001_TAG266);
        tags.put('SFM001-iPad_Show_All_Sections_By_Default', system.label.SFM001_TAG267);
        tags.put('SFM001-iPad_Ask_to_create_new_event', system.label.SFM001_TAG268);
        tags.put('SFM001-iPad_Enable_Chatter', system.label.SFM001_TAG269);
        tags.put('SFM001-iPad_Enable_Attachments', system.label.SFM001_TAG270);
        tags.put('SFM001-iPad_Show_Account_History', system.label.SFM001_TAG271);
        tags.put('SFM001-iPad_Show_Product_History', system.label.SFM001_TAG272);
        tags.put('SFM001-iPad_Troubleshooting', system.label.SFM001_TAG273);
        tags.put('SFM001-enable_Chatter', system.label.SFM001_TAG269);
        tags.put('SFM001-No_Of_Display_Columns', system.label.SFM001_TAG274);
        tags.put('SFM001-isSLAEnabled', system.label.SFM001_TAG275);
        tags.put('SFM001-TAG276', system.label.SFM001_TAG276);
        tags.put('SFM001-iPad_Enable_Service_Report_View', system.label.SFM001_TAG277);
        tags.put('SFM001-iPad_Enable_Service_Report_Generation', system.label.SFM001_TAG278);
        tags.put('SFM001-Min_Value', system.label.SFM001_TAG279);
        tags.put('SFM001-Max_Value', system.label.SFM001_TAG280);
        tags.put('SFM001-Control_Type', system.label.SFM001_TAG281);
        tags.put('SFM001-TAG282', system.label.SFM001_TAG282);
        tags.put('SFM001-TAG283', system.label.SFM001_TAG283);
        tags.put('SFM001-TAG284', system.label.SFM001_TAG284);
        tags.put('SFM001-TAG285', system.label.SFM001_TAG285);
        tags.put('SFM001-Context_Source_Object', system.label.SFM001_TAG286);
        tags.put('SFM001-TAG287', system.label.SFM001_TAG287);

        tags.put('SFM001-iPad_Summary_Title_Bar', system.label.SFM001_TAG546);
        tags.put('SFM001-iPad_Enable_Summary_View', system.label.SFM001_TAG547);

        tags.put('SFM001-iPad_Summary_Title', system.label.SFM001_TAG548);
        tags.put('SFM001-iPad_Include_Event_Time_Place', system.label.SFM001_TAG549);
        tags.put('SFM001-iPad_Include_Contact', system.label.SFM001_TAG550);
        tags.put('SFM001-iPad_Summary_IncludeField_1', system.label.SFM001_TAG551);
        tags.put('SFM001-iPad_Summary_IncludeField_2', system.label.SFM001_TAG551);
        tags.put('SFM001-iPad_Summary_IncludeField_3', system.label.SFM001_TAG551);
        tags.put('SFM001-TAG552', system.label.SFM001_TAG552);
        tags.put('SFM001-TAG553', system.label.SFM001_TAG553);
        tags.put('SFM001-TAG554', system.label.SFM001_TAG554);
        tags.put('SFM001-TAG555', system.label.SFM001_TAG555);
        tags.put('SFM001-TAG556', system.label.SFM001_TAG556);
        tags.put('SFM001-TAG557', system.label.SFM001_TAG557);
        tags.put('SFM001-TAG558', system.label.SFM001_TAG558);
        //New Tags for SFM Expression.
        tags.put('SFM001-TAG288', system.label.SFM001_TAG288);
        tags.put('SFM001-TAG289', system.label.SFM001_TAG289);
        tags.put('SFM001-TAG290', system.label.SFM001_TAG290);
        tags.put('SFM001-HLPURL6', system.label.SFM001_HLPURL6);
        tags.put('SFM001-TAG291', system.label.SFM001_TAG291);
        tags.put('SFM001-Show_In_Web', system.label.SFM001_TAG292);
        tags.put('SFM001-Show_In_iPad', system.label.SFM001_TAG293);
        tags.put('SFM001-Code_Snippets', system.label.SFM001_TAG294);
        tags.put('SFM001-TAG295', system.label.SFM001_TAG295);
        tags.put('SFM001-TAG296', system.label.SFM001_TAG296);
        tags.put('SFM001-TAG297', system.label.SFM001_TAG297);

        tags.put('SFM001-TAG298', system.label.SFM001_TAG298);
        tags.put('SFM001-TAG299', system.label.SFM001_TAG299);
        tags.put('SFM001-TAG300', system.label.SFM001_TAG300);
        tags.put('SFM001-TAG301', system.label.SFM001_TAG301);
        tags.put('SFM001-Event_Option', system.label.SFM001_TAG302);
        tags.put('SFM001-TAG303', system.label.SFM001_TAG303);
        tags.put('SFM001-TAG304', system.label.SFM001_TAG304);
        tags.put('SFM001-TAG305', system.label.SFM001_TAG305);
        tags.put('SFM001-TAG306', system.label.SFM001_TAG306);
        tags.put('SFM001-TAG307', system.label.SFM001_TAG307);
        tags.put('SFM001-TAG308', system.label.SFM001_TAG308);
        tags.put('SFM001-TAG309', system.label.SFM001_TAG309);
        tags.put('SFM001-TAG310', system.label.SFM001_TAG310);
        tags.put('SFM001-TAG311', system.label.SFM001_TAG311);
        tags.put('SFM001-TAG312', system.label.SFM001_TAG312);
        tags.put('SFM001-TAG313', system.label.SFM001_TAG313);
        tags.put('SFM001-TAG314', system.label.SFM001_TAG314);
        tags.put('SFM001-TAG315', system.label.SFM001_TAG315);
        tags.put('SFM001-TAG316', system.label.SFM001_TAG316);
        tags.put('SFM001-TAG317', system.label.SFM001_TAG317);
        tags.put('SFM001-TAG318', system.label.SFM001_TAG318);
        tags.put('SFM001-TAG319', system.label.SFM001_TAG319);
        tags.put('SFM001-TAG320', system.label.SFM001_TAG320);
        tags.put('SFM001-TAG321', system.label.SFM001_TAG321);
        tags.put('SFM001-TAG322', system.label.SFM001_TAG322);
        tags.put('SFM001-TAG323', system.label.SFM001_TAG323);
        tags.put('SFM001-TAG324', system.label.SFM001_TAG324);
        tags.put('SFM001-TAG325', system.label.SFM001_TAG325);
        tags.put('SFM001-TAG326', system.label.SFM001_TAG326);
        tags.put('SFM001-TAG327', system.label.SFM001_TAG327);
        tags.put('SFM001-TAG328', system.label.SFM001_TAG328);
        tags.put('SFM001-TAG329', system.label.SFM001_TAG329);
        tags.put('SFM001-TAG330', system.label.SFM001_TAG320);
        tags.put('SFM001-TAG331', system.label.SFM001_TAG331);
        tags.put('SFM001-TAG332', system.label.SFM001_TAG332);
        tags.put('SFM001-TAG333', system.label.SFM001_TAG333);
        tags.put('SFM001-TAG334', system.label.SFM001_TAG334);
        tags.put('SFM001-TAG335', system.label.SFM001_TAG335);
        tags.put('SFM001-TAG336', system.label.SFM001_TAG336);
        tags.put('SFM001-TAG337', system.label.SFM001_TAG337);
        tags.put('SFM001-TAG338', system.label.SFM001_TAG338);
        tags.put('SFM001-TAG339', system.label.SFM001_TAG339);
        tags.put('SFM001-TAG340', system.label.SFM001_TAG340);
        tags.put('SFM001-TAG341', system.label.SFM001_TAG341);
        tags.put('SFM001-TAG342', system.label.SFM001_TAG342);
        tags.put('SFM001-TAG343', system.label.SFM001_TAG343);
        tags.put('SFM001-TAG344', system.label.SFM001_TAG344);
        tags.put('SFM001-TAG345', system.label.SFM001_TAG345);
        tags.put('SFM001-TAG346', system.label.SFM001_TAG346);

        //Tags related to Business Rules.
        tags.put('SFM001-TAG352', system.label.SFM001_TAG352);
        tags.put('SFM001-TAG353', system.label.SFM001_TAG353);
        tags.put('SFM001-TAG354', system.label.SFM001_TAG354);
        tags.put('SFM001-TAG355', system.label.SFM001_TAG355);
        tags.put('SFM001-TAG356', system.label.SFM001_TAG356);
        tags.put('SFM001-TAG357', system.label.SFM001_TAG357);
        tags.put('SFM001-TAG358', system.label.SFM001_TAG358);
        tags.put('SFM001-TAG359', system.label.SFM001_TAG359);
        tags.put('SFM001-TAG360', system.label.SFM001_TAG360);
        tags.put('SFM001-TAG361', system.label.SFM001_TAG361);
        tags.put('SFM001-TAG362', system.label.SFM001_TAG362);
        tags.put('SFM001-TAG363', system.label.SFM001_TAG363);
        tags.put('SFM001-TAG364', system.label.SFM001_TAG364);
        tags.put('SFM001-TAG365', system.label.SFM001_TAG365);
        tags.put('SFM001-TAG366', system.label.SFM001_TAG366);
        tags.put('SFM001-TAG367', system.label.SFM001_TAG367);
        tags.put('SFM001-TAG368', system.label.SFM001_TAG368);
        tags.put('SFM001-TAG369', system.label.SFM001_TAG369);
        tags.put('SFM001-TAG370', system.label.SFM001_TAG370);
        tags.put('SFM001-TAG371', system.label.SFM001_TAG371);
        tags.put('SFM001-TAG372', system.label.SFM001_TAG372);
        tags.put('SFM001-TAG373', system.label.SFM001_TAG373);
        tags.put('SFM001-TAG374', system.label.SFM001_TAG374);
        tags.put('SFM001-TAG375', system.label.SFM001_TAG375);
        tags.put('SFM001-TAG376', system.label.SFM001_TAG376);
        tags.put('SFM001-TAG377', system.label.SFM001_TAG377);
        tags.put('SFM001-TAG378', system.label.SFM001_TAG378);
        tags.put('SFM001-TAG379', system.label.SFM001_TAG379);
        tags.put('SFM001-TAG380', system.label.SFM001_TAG380);
        tags.put('SFM001-TAG381', system.label.SFM001_TAG381);
        tags.put('SFM001-TAG397', system.label.SFM001_TAG397);
        tags.put('SFM001-TAG398', system.label.SFM001_TAG398);
        tags.put('SFM001-TAG399', system.label.SFM001_TAG399);
        tags.put('SFM001-TAG400', system.label.SFM001_TAG400);
        tags.put('SFM001-TAG401', system.label.SFM001_TAG401);
        tags.put('SFM001-TAG402', system.label.SFM001_TAG402);
        tags.put('SFM001-TAG403', system.label.SFM001_TAG403);
        tags.put('SFM001-TAG404', system.label.SFM001_TAG404);
        tags.put('SFM001-TAG405', system.label.SFM001_TAG405);
        tags.put('SFM001-TAG406', system.label.SFM001_TAG406);
        tags.put('SFM001-TAG407', system.label.SFM001_TAG407);
        tags.put('SFM001-TAG408', system.label.SFM001_TAG408);
        tags.put('SFM001-TAG409', system.label.SFM001_TAG409);
        tags.put('SFM001-TAG410', system.label.SFM001_TAG410);
        tags.put('SFM001-TAG411', system.label.SFM001_TAG411);
        tags.put('SFM001-TAG412', system.label.SFM001_TAG412);
        tags.put('SFM001-TAG413', system.label.SFM001_TAG413);
        tags.put('SFM001-TAG414', system.label.SFM001_TAG414);
        tags.put('SFM001-TAG415', system.label.SFM001_TAG415);
        tags.put('SFM001-TAG416', system.label.SFM001_TAG416);
        tags.put('SFM001-TAG417', system.label.SFM001_TAG417);
        tags.put('SFM001-TAG418', system.label.SFM001_TAG418);
        tags.put('SFM001-TAG419', system.label.SFM001_TAG419);
        tags.put('SFM001-TAG420', system.label.SFM001_TAG420);
        tags.put('SFM001-TAG421', system.label.SFM001_TAG421);
        tags.put('SFM001-TAG422', system.label.SFM001_TAG422);
        tags.put('SFM001-TAG423', system.label.SFM001_TAG423);
        tags.put('SFM001-TAG424', system.label.SFM001_TAG424);
        tags.put('SFM001-TAG425', system.label.SFM001_TAG425);
        tags.put('SFM001-TAG426', system.label.SFM001_TAG426);
        tags.put('SFM001-TAG427', system.label.SFM001_TAG427);
        tags.put('SFM001-TAG428', system.label.SFM001_TAG428);
        tags.put('SFM001-TAG429', system.label.SFM001_TAG429);
        tags.put('SFM001-TAG430', system.label.SFM001_TAG430);
        tags.put('SFM001-TAG431', system.label.SFM001_TAG431);
        tags.put('SFM001-TAG432', system.label.SFM001_TAG432);
        tags.put('SFM001-TAG433', system.label.SFM001_TAG433);
        tags.put('SFM001-TAG434', system.label.SFM001_TAG434);
        tags.put('SFM001-TAG435', system.label.SFM001_TAG435);
        tags.put('SFM001-TAG436', system.label.SFM001_TAG436);
        tags.put('SFM001-TAG437', system.label.SFM001_TAG437);
        tags.put('SFM001-TAG438', system.label.SFM001_TAG438);
        tags.put('SFM001-TAG439', system.label.SFM001_TAG439);
        tags.put('SFM001-TAG440', system.label.SFM001_TAG440);
        tags.put('SFM001-TAG441', system.label.SFM001_TAG441);
        tags.put('SFM001-TAG442', system.label.SFM001_TAG442);
        tags.put('SFM001-TAG443', system.label.SFM001_TAG443);
        tags.put('SFM001-TAG444', system.label.SFM001_TAG444);
        tags.put('SFM001-TAG453', system.label.SFM001_TAG453);
        tags.put('SFM001-TAG454', system.label.SFM001_TAG454);
        tags.put('SFM001-TAG455', system.label.SFM001_TAG455);
        tags.put('SFM001-TAG456', system.label.SFM001_TAG456);
        tags.put('SFM001-TAG457', system.label.SFM001_TAG457);
        tags.put('SFM001-TAG458', system.label.SFM001_TAG458);
        tags.put('SFM001-TAG459', system.label.SFM001_TAG459);
        tags.put('SFM001-TAG460', system.label.SFM001_TAG460);
        tags.put('SFM001-TAG461', system.label.SFM001_TAG461);
        tags.put('SFM001-TAG462', system.label.SFM001_TAG462);
        tags.put('SFM001-TAG463', system.label.SFM001_TAG463);
        tags.put('SFM001-TAG464', system.label.SFM001_TAG464);
        tags.put('SFM001-TAG465', system.label.SFM001_TAG465);
        tags.put('SFM001-TAG466', system.label.SFM001_TAG466);
        tags.put('SFM001-TAG467', system.label.SFM001_TAG467);
        tags.put('SFM001-TAG469', system.label.SFM001_TAG469);
        tags.put('SFM001-TAG470', system.label.SFM001_TAG470);
        tags.put('SFM001-TAG471', system.label.SFM001_TAG471);
        tags.put('SFM001-TAG472', system.label.SFM001_TAG472);
        tags.put('SFM001-TAG473', system.label.SFM001_TAG473);
        tags.put('SFM001-TAG474', system.label.SFM001_TAG474);
        tags.put('SFM001-TAG475', system.label.SFM001_TAG475);
        tags.put('SFM001-TAG476', system.label.SFM001_TAG476);//to generate a Checklist / Survey type of Process
        tags.put('SFM001-TAG477', system.label.SFM001_TAG477);
        tags.put('SFM001-TAG478', system.label.SFM001_TAG478);
        tags.put('SFM001-TAG479', system.label.SFM001_TAG479);
        tags.put('SFM001-TAG480', system.label.SFM001_TAG480);
        tags.put('SFM001-TAG481', system.label.SFM001_TAG481);
        tags.put('SFM001-TAG482', system.label.SFM001_TAG482);
        tags.put('SFM001-TAG483', system.label.SFM001_TAG483);
        tags.put('SFM001-TAG484', system.label.SFM001_TAG484);
        tags.put('SFM001-TAG485', system.label.SFM001_TAG485);
        tags.put('SFM001-TAG486', system.label.SFM001_TAG486);
        tags.put('SFM001-TAG487', system.label.SFM001_TAG487);
        tags.put('SFM001-TAG488', system.label.SFM001_TAG488);
        tags.put('SFM001-TAG553', system.label.SFM001_TAG553);
        tags.put('SFM001-TAG554', system.label.SFM001_TAG554);
        tags.put('SFM001-TAG555', system.label.SFM001_TAG555);
        tags.put('SFM001-TAG556', system.label.SFM001_TAG556);
        tags.put('SFM001-TAG557', system.label.SFM001_TAG557);
        tags.put('SFM001-TAG558', system.label.SFM001_TAG558);
        tags.put('SFM001-TAG559', system.label.SFM001_TAG559);
        tags.put('SFM001-TAG560', system.label.SFM001_TAG560);
        tags.put('SFM001-TAG561', system.label.SFM001_TAG561);
        tags.put('SFM001-TAG562', system.label.SFM001_TAG562);
        tags.put('SFM001-TAG563', system.label.SFM001_TAG563);
        tags.put('SFM001-TAG564', system.label.SFM001_TAG564);
        tags.put('SFM001-TAG565', system.label.SFM001_TAG565);
        tags.put('SFM001-TAG566', system.label.SFM001_TAG566);
        tags.put('SFM001-TAG567', system.label.SFM001_TAG567);
        tags.put('SFM001-TAG568', system.label.SFM001_TAG568);
        tags.put('SFM001-TAG569', system.label.SFM001_TAG569);
        tags.put('SFM001-TAG570', system.label.SFM001_TAG570);
        tags.put('SFM001-TAG571', system.label.SFM001_TAG571);
        tags.put('SFM001-TAG572', system.label.SFM001_TAG572);
        tags.put('SFM001-TAG573', system.label.SFM001_TAG573);
        tags.put('SFM001-TAG574', system.label.SFM001_TAG574);
        tags.put('SFM001-TAG575', system.label.SFM001_TAG575);
        tags.put('SFM001-TAG576', system.label.SFM001_TAG576);
        tags.put('SFM001-TAG577', system.label.SFM001_TAG577);
        tags.put('SFM001-TAG578', system.label.SFM001_TAG578);
        tags.put('SFM001-TAG579', system.label.SFM001_TAG579);
        tags.put('SFM001-TAG580', system.label.SFM001_TAG580);
        tags.put('SFM001-TAG581', system.label.SFM001_TAG581);
        tags.put('SFM001-TAG582', system.label.SFM001_TAG582);
        tags.put('SFM001-TAG583', system.label.SFM001_TAG583);
        tags.put('SFM001-TAG584', system.label.SFM001_TAG584);
        tags.put('SFM001-TAG585', system.label.SFM001_TAG585);
        tags.put('SFM001-TAG586', system.label.SFM001_TAG586);

        tags.put('SFM001-TAG587', system.label.SFM001_TAG587);
        tags.put('SFM001-TAG588', system.label.SFM001_TAG588);
        tags.put('SFM001-TAG589', system.label.SFM001_TAG589);
        tags.put('SFM001-TAG590', system.label.SFM001_TAG590);
        tags.put('SFM001-TAG591', system.label.SFM001_TAG591);
        tags.put('SFM001-TAG592', system.label.SFM001_TAG592);
        tags.put('SFM001-TAG593', system.label.SFM001_TAG593);
        tags.put('SFM001-TAG594', system.label.SFM001_TAG594);
        tags.put('SFM001-TAG595', system.label.SFM001_TAG595);
        tags.put('SFM001-TAG596', system.label.SFM001_TAG596);
        tags.put('SFM001-TAG597', system.label.SFM001_TAG597);
        tags.put('SFM001-TAG598', system.label.SFM001_TAG598);
        tags.put('SFM001-TAG599', system.label.SFM001_TAG599);
        tags.put('SFM001-TAG600', system.label.SFM001_TAG600);
        tags.put('SFM001-TAG601', system.label.SFM001_TAG601);
        tags.put('SFM001-TAG602', system.label.SFM001_TAG602);
        tags.put('SFM001-TAG604', system.label.SFM001_TAG604);
        tags.put('SFM001-TAG605', system.label.SFM001_TAG605);
        tags.put('SFM001-TAG606', system.label.SFM001_TAG606);
        tags.put('SFM001-TAG607', system.label.SFM001_TAG607);
        tags.put('SFM001-TAG608', system.label.SFM001_TAG608);
        tags.put('SFM001-TAG609', system.label.SFM001_TAG609);
        tags.put('SFM001-TAG610', system.label.SFM001_TAG610);
        tags.put('SFM001-TAG611', system.label.SFM001_TAG611);
        tags.put('SFM001-TAG612', system.label.SFM001_TAG612);
        tags.put('SFM001-TAG613', system.label.SFM001_TAG613);
        tags.put('SFM001-TAG614', system.label.SFM001_TAG614);
        tags.put('SFM001-TAG615', system.label.SFM001_TAG615);


        tags.put('SFM001-HLPURL16', system.label.SFM001_HLPURL16);
        tags.put('SFM001-HLPURL17', system.label.SFM001_HLPURL17);

        //------Start------Added for the story BAC-3774
        tags.put('SFM001-TAG616', system.label.SFM001_TAG616);
        tags.put('SFM001-TAG617', system.label.SFM001_TAG617);
        tags.put('SFM001-TAG618', system.label.SFM001_TAG618);
        tags.put('SFM001-TAG619', system.label.SFM001_TAG619);
        tags.put('SFM001-TAG620', system.label.SFM001_TAG620);
        tags.put('SFM001-TAG621', system.label.SFM001_TAG621);
        tags.put('SFM001-TAG622', system.label.SFM001_TAG622);
        tags.put('SFM001-TAG623', system.label.SFM001_TAG623);
        tags.put('SFM001-TAG624', system.label.SFM001_TAG624);
        tags.put('SFM001-TAG625', system.label.SFM001_TAG625);
        tags.put('SFM001-TAG626', system.label.SFM001_TAG626);
        tags.put('SFM001-TAG627', system.label.SFM001_TAG627);
        tags.put('SFM001-TAG628', system.label.SFM001_TAG628);
        tags.put('SFM001-TAG629', system.label.SFM001_TAG629);
        tags.put('SFM001-TAG630', system.label.SFM001_TAG630);
        tags.put('SFM001-TAG631', system.label.SFM001_TAG631);
        tags.put('SFM001-TAG632', system.label.SFM001_TAG632);
        tags.put('SFM001-TAG633', system.label.SFM001_TAG633);
        tags.put('SFM001-TAG634', system.label.SFM001_TAG634);
        tags.put('SFM001-TAG635', system.label.SFM001_TAG635);
        tags.put('SFM001-TAG636', system.label.SFM001_TAG636);
        tags.put('SFM001-TAG637', system.label.SFM001_TAG637);
        tags.put('SFM001-TAG638', system.label.SFM001_TAG638);
        tags.put('SFM001-TAG639', system.label.SFM001_TAG639);
        tags.put('SFM001-TAG640', system.label.SFM001_TAG640);
        tags.put('SFM001-TAG641', system.label.SFM001_TAG641);
        tags.put('SFM001-TAG642', system.label.SFM001_TAG642);
        tags.put('SFM001-TAG643', system.label.SFM001_TAG643);
        tags.put('SFM001-TAG644', system.label.SFM001_TAG644);
        tags.put('SFM001-TAG645', system.label.SFM001_TAG645);
        tags.put('SFM001-TAG646', system.label.SFM001_TAG646);
        tags.put('SFM001-TAG657', system.label.SFM001_TAG657);
        tags.put('SFM001-TAG658', system.label.SFM001_TAG658);
        tags.put('SFM001-TAG659', system.label.SFM001_TAG659);
        tags.put('SFM001-TAG660', system.label.SFM001_TAG660);
        tags.put('SFM001-TAG703', system.label.SFM001_TAG703); //File Properties ---BAC-3573
        tags.put('SFM001-TAG704', system.label.SFM001_TAG704); //Enable Version Control ---BAC-3573
        tags.put('SFM001-TAG705', system.label.SFM001_TAG705); //This will be used to control file versioning for the SmartDoc process. ---BAC-3573
        tags.put('SFM001-TAG732', system.label.SFM001_TAG732); //BAC-4329
        tags.put('SFM001-TAG733', system.label.SFM001_TAG733); //BAC-4329
        tags.put('SFM001-TAG734', system.label.SFM001_TAG734); //BAC-4329
        tags.put('SFM001-TAG735', system.label.SFM001_TAG735);
        tags.put('SFM001-TAG736', system.label.SFM001_TAG736);


        tags.put('SFM001-HLPURL16', system.label.SFM001_HLPURL16);
        tags.put('SFM001-HLPURL17', system.label.SFM001_HLPURL17);


        //Tags for Linked Process
        tags.put('SFM001-TAG382', system.label.SFM001_TAG382);

        //Advance Lookup Filter
        tags.put('SFM001-TAG383', system.label.SFM001_TAG383);
        tags.put('SFM001-TAG384', system.label.SFM001_TAG384);
        tags.put('SFM001-TAG385', system.label.SFM001_TAG385);
        tags.put('SFM001-TAG386', system.label.SFM001_TAG386);
        tags.put('SFM001-TAG387', system.label.SFM001_TAG387);
        tags.put('SFM001-TAG388', system.label.SFM001_TAG388);
        tags.put('SFM001-TAG389', system.label.SFM001_TAG389);
        tags.put('SFM001-TAG390', system.label.SFM001_TAG390);
        tags.put('SFM001-TAG391', system.label.SFM001_TAG391);
        tags.put('SFM001-TAG392', system.label.SFM001_TAG392);
        tags.put('SFM001-TAG393', system.label.SFM001_TAG393);
        tags.put('SFM001-TAG394', system.label.SFM001_TAG394);
        tags.put('SFM001-TAG395', system.label.SFM001_TAG395);
        tags.put('SFM001-Object_Mapping', system.label.SFM001_TAG396);

        tags.put('SFM001-HLPURL7', system.label.SFM001_HLPURL7);
        tags.put('SFM001-HLPURL', system.label.SFM001_HLPURL);
        tags.put('SFM001-HLPURL2', system.label.SFM001_HLPURL2);
        tags.put('SFM001-HLPURL3', system.label.SFM001_HLPURL3);
        tags.put('SFM001-HLPURL4', system.label.SFM001_HLPURL4);
        tags.put('SFM001-HLPURL5', system.label.SFM001_HLPURL5);

        tags.put('SFM001-HLPURL8', system.label.SFM001_HLPURL8);
        tags.put('SFM001-HLPURL9', system.label.SFM001_HLPURL9);
        tags.put('SFM001-HLPURL10', system.label.SFM001_HLPURL10);
        tags.put('SFM001-HLPURL11', system.label.SFM001_HLPURL11);
        tags.put('SFM001-HLPURL12', system.label.SFM001_HLPURL12);
        tags.put('SFM001-HLPURL13', system.label.SFM001_HLPURL13);
        tags.put('SFM001-HLPURL14', system.label.SFM001_HLPURL14);
        tags.put('SFM001-HLPURL15', system.label.SFM001_HLPURL15);

        /*
            Checklist Tags
        */
        tags.put('SFM001-TAG510', system.label.SFM001_TAG510);
        tags.put('SFM001-TAG511', system.label.SFM001_TAG511);
        tags.put('SFM001-TAG512', system.label.SFM001_TAG512);
        tags.put('SFM001-TAG513', system.label.SFM001_TAG513);
        tags.put('SFM001-TAG514', system.label.SFM001_TAG514);
        tags.put('SFM001-TAG515', system.label.SFM001_TAG515);
        tags.put('SFM001-TAG516', system.label.SFM001_TAG516);
        tags.put('SFM001-TAG517', system.label.SFM001_TAG517);
        tags.put('SFM001-TAG518', system.label.SFM001_TAG518);
        tags.put('SFM001-TAG519', system.label.SFM001_TAG519);
        tags.put('SFM001-TAG520', system.label.SFM001_TAG520);
        tags.put('SFM001-TAG521', system.label.SFM001_TAG521);
        tags.put('SFM001-TAG522', system.label.SFM001_TAG522);
        tags.put('SFM001-TAG523', system.label.SFM001_TAG523);
        tags.put('SFM001-TAG524', system.label.SFM001_TAG524);
        tags.put('SFM001-TAG525', system.label.SFM001_TAG525);
        tags.put('SFM001-TAG526', system.label.SFM001_TAG526);
        tags.put('SFM001-TAG527', system.label.SFM001_TAG527);
        tags.put('SFM001-TAG528', system.label.SFM001_TAG528);
        tags.put('SFM001-TAG529', system.label.SFM001_TAG529);
        tags.put('SFM001-TAG530', system.label.SFM001_TAG530);
        tags.put('SFM001-TAG531', system.label.SFM001_TAG531);
        tags.put('SFM001-TAG532', system.label.SFM001_TAG532);
        tags.put('SFM001-TAG533', system.label.SFM001_TAG533);
        tags.put('SFM001-TAG534', system.label.SFM001_TAG534);
        tags.put('SFM001-TAG535', system.label.SFM001_TAG535);
        tags.put('SFM001-TAG536', system.label.SFM001_TAG536);
        tags.put('SFM001-TAG537', system.label.SFM001_TAG537);
        tags.put('SFM001-TAG538', system.label.SFM001_TAG538);
        tags.put('SFM001-TAG539', system.label.SFM001_TAG539);
        tags.put('SFM001-TAG540', system.label.SFM001_TAG540);
        tags.put('SFM001-TAG541', system.label.SFM001_TAG541);
        tags.put('SFM001-TAG542', system.label.SFM001_TAG542);
        tags.put('SFM001-TAG543', system.label.SFM001_TAG543);
        tags.put('SFM001-TAG544', system.label.SFM001_TAG544);
        tags.put('SFM001-TAG545', system.label.SFM001_TAG545);

        /*
            Formula Tags
        */
        tags.put('SFM001-TAG489', system.label.SFM001_TAG489);
        tags.put('SFM001-TAG490', system.label.SFM001_TAG490);
        tags.put('SFM001-TAG491', system.label.SFM001_TAG491);
        tags.put('SFM001-TAG492', system.label.SFM001_TAG492);
        tags.put('SFM001-TAG493', system.label.SFM001_TAG493);
        tags.put('SFM001-TAG494', system.label.SFM001_TAG494);
        tags.put('SFM001-TAG495', system.label.SFM001_TAG495);
        tags.put('SFM001-TAG496', system.label.SFM001_TAG496);
        tags.put('SFM001-TAG497', system.label.SFM001_TAG497);
        tags.put('SFM001-TAG498', system.label.SFM001_TAG498);
        tags.put('SFM001-TAG499', system.label.SFM001_TAG499);
        tags.put('SFM001-TAG500', system.label.SFM001_TAG500);
        tags.put('SFM001-TAG501', system.label.SFM001_TAG501);
        tags.put('SFM001-TAG502', system.label.SFM001_TAG502);
        tags.put('SFM001-TAG503', system.label.SFM001_TAG503);
        tags.put('SFM001-TAG504', system.label.SFM001_TAG504);
        tags.put('SFM001-TAG505', system.label.SFM001_TAG505);
        tags.put('SFM001-TAG506', system.label.SFM001_TAG506);
        tags.put('SFM001-TAG507', system.label.SFM001_TAG507);
        tags.put('SFM001-TAG508', system.label.SFM001_TAG508);
        tags.put('SFM001-TAG509', system.label.SFM001_TAG509);

    }

    public static void getNewDesignerTags(Map<String,String> tags) {
        tags.put('SFM001-TAG647', system.label.SFM001_TAG647); //Designer 2.0 - New Tag for 'Select a Transaction'
        tags.put('SFM001-TAG648', system.label.SFM001_TAG648); //Designer 2.0 - New Tag for 'Search Transaction'
        tags.put('SFM001-TAG649', system.label.SFM001_TAG649); //Designer 2.0 - New Tag for 'Other Transaction'
        tags.put('SFM001-TAG650', system.label.SFM001_TAG650); //Designer 2.0 - New Tag for 'To create Source to Target records'
        tags.put('SFM001-TAG651', system.label.SFM001_TAG651); //Designer 2.0 - New Tag for 'To create and map child lines only'
        tags.put('SFM001-TAG652', system.label.SFM001_TAG652); //Designer 2.0 - New Tag for 'To create and manage child lines'
        tags.put('SFM001-TAG653', system.label.SFM001_TAG653); //Designer 2.0 - New Tag for 'SFM TRANSACTION DESIGNER'
        tags.put('SFM001-TAG654', system.label.SFM001_TAG654); //Designer 2.0 - New Tag for 'Cannot be Edited'
        tags.put('SFM001-TAG655', system.label.SFM001_TAG655); //Designer 2.0 - New Tag for 'DEFAULT VIEWS'
        tags.put('SFM001-TAG656', system.label.SFM001_TAG656); //Designer 2.0 - New Tag for 'Recently Used'
        tags.put('SFM001-TAG661', system.label.SFM001_TAG661); //Designer 2.0 - New Tag for 'Where Used'
        tags.put('SFM001-TAG662', system.label.SFM001_TAG662); //Designer 2.0 - New Tag for 'Below are the different areas where this transaction is being used'
        tags.put('SFM001-TAG663', system.label.SFM001_TAG663); //Designer 2.0 - New Tag for 'Refresh Metadata'
        tags.put('SFM001-TAG664', system.label.SFM001_TAG664); //Designer 2.0 - New Tag for 'New Expression'
        tags.put('SFM001-TAG665', system.label.SFM001_TAG665); //Designer 2.0 - New Tag for 'Untitled Expression'
        tags.put('SFM001-TAG666', system.label.SFM001_TAG666); //Designer 2.0 - New Tag for 'TRANSACTION NAME'
        tags.put('SFM001-TAG667', system.label.SFM001_TAG667); //Designer 2.0 - New Tag for 'This is where you can tag to remember or relate the transaction to a vertical, type, etc.'
        tags.put('SFM001-TAG668', system.label.SFM001_TAG668); //Designer 2.0 - New Tag for 'Are you sure you want to delete this   '
        tags.put('SFM001-TAG669', system.label.SFM001_TAG669); //Designer 2.0 - New Tag for 'No dependencies have been found.'
        tags.put('SFM001-TAG670', system.label.SFM001_TAG670); //Designer 2.0 - New Tag for 'No results have been found.'
        tags.put('SFM001-TAG671', system.label.SFM001_TAG671); //Designer 2.0 - New Tag for 'Confirm'
        tags.put('SFM001-TAG672', system.label.SFM001_TAG672); //Designer 2.0 - New Tag for 'Search Tags'
        tags.put('SFM001-TAG673', system.label.SFM001_TAG673); //Designer 2.0 - New Tag for 'New Validation Rule'
        tags.put('SFM001-TAG674', system.label.SFM001_TAG674); //Designer 2.0 - New Tag for 'Standard Validation Rule'
        tags.put('SFM001-TAG675', system.label.SFM001_TAG675); //Designer 2.0 - New Tag for 'Standard Expression'
        tags.put('SFM001-TAG676', system.label.SFM001_TAG676); //Designer 2.0 - New Tag for 'Expression will get saved only when Salesforce query size limit is within 20,000 characters and ‘Advance Expression’ limit is within 255 characters.'
        tags.put('SFM001-TAG677', system.label.SFM001_TAG677); //Designer 2.0 - New Tag for 'Literals'
        tags.put('SFM001-TAG678', system.label.SFM001_TAG678); //Designer 2.0 - New Tag for 'Last N Days'
        tags.put('SFM001-TAG679', system.label.SFM001_TAG679); //Designer 2.0 - New Tag for 'Next N Days'
        tags.put('SFM001-TAG680', system.label.SFM001_TAG680); //Designer 2.0 - New Tag for 'Other Expression'
        tags.put('SFM001-TAG681', system.label.SFM001_TAG681); //Designer 2.0 - New Tag for 'Recent Items'
        tags.put('SFM001-TAG682', system.label.SFM001_TAG682); //Designer 2.0 - New Tag for 'Please name the expression'
        tags.put('SFM001-TAG683', system.label.SFM001_TAG683); //Designer 2.0 - New Tag for 'The expression is not valid.'
        tags.put('SFM001-TAG684', system.label.SFM001_TAG684); //Designer 2.0 - New Tag for 'There are multiple errors in the fields.'
        tags.put('SFM001-TAG685', system.label.SFM001_TAG685); //Designer 2.0 - New Tag for 'Name already exists.'
        tags.put('SFM001-TAG686', system.label.SFM001_TAG686); //Designer 2.0 - New Tag for 'Mappings'
        tags.put('SFM001-TAG687', system.label.SFM001_TAG687); //Designer 2.0 - New Tag for 'Mapping Name'
        tags.put('SFM001-TAG688', system.label.SFM001_TAG688); //Designer 2.0 - New Tag for 'Untitled'
        tags.put('SFM001-TAG689', system.label.SFM001_TAG689); //Designer 2.0 - New Tag for 'Data Validation Rule '
        tags.put('SFM001-TAG690', system.label.SFM001_TAG690); //Designer 2.0 - New Tag for 'Other Validation Rule'
        tags.put('SFM001-TAG691', system.label.SFM001_TAG691); //Designer 2.0 - New Tag for 'The Entity Name you have entered already exists. Please enter a unique Name'
        tags.put('SFM001-TAG692', system.label.SFM001_TAG692); //Designer 2.0 - New Tag for 'View Expression'
        tags.put('SFM001-TAG693', system.label.SFM001_TAG693); //Designer 2.0 - New Tag for 'Field mapping from Source to Target Record'
        tags.put('SFM001-TAG694', system.label.SFM001_TAG694); //Designer 2.0 - New Tag for 'This mapping will be used when a Source object’s fields are being mapped to a Target object’s field.'
        tags.put('SFM001-TAG695', system.label.SFM001_TAG695); //Designer 2.0 - New Tag for 'For example'
        tags.put('SFM001-TAG696', system.label.SFM001_TAG696); //Designer 2.0 - New Tag for 'When a Shipment Order is created from a Work Order, this mapping allows the values in fields such as 'Account' and 'Location' to map to the Shipment Order's 'Account' and 'To Location'.'
        tags.put('SFM001-TAG697', system.label.SFM001_TAG697); //Designer 2.0 - New Tag for 'Select Source Object'
        tags.put('SFM001-TAG698', system.label.SFM001_TAG698); //Designer 2.0 - New Tag for 'Select Target Object'
        tags.put('SFM001-TAG699', system.label.SFM001_TAG699); //Designer 2.0 - New Tag for 'Field mapping for new Record'
        tags.put('SFM001-TAG700', system.label.SFM001_TAG700); //Designer 2.0 - New Tag for 'This mapping will be used to set defined value(s) when a new Child Record is being created.'
        tags.put('SFM001-TAG701', system.label.SFM001_TAG701); //Designer 2.0 - New Tag for 'When a technician is adding a new Part Usage line on a Work Order, the ‘Line Qty’ field value can be set to be '1'.'
        tags.put('SFM001-TAG702', system.label.SFM001_TAG702); //Designer 2.0 - New Tag for 'Would you like to create'
        tags.put('SFM001-TAG706', system.label.SFM001_TAG706); //Designer 2.0 - New Tag for 'Placeholder Message '
        tags.put('SFM001-TAG707', system.label.SFM001_TAG707); //Designer 2.0 - New Tag for 'This object no longer exists. Click OK to continue '
        tags.put('SFM001-TAG708', system.label.SFM001_TAG708); //Designer 2.0 - New Tag for 'Name must be at least 8 characters long'
        tags.put('SFM001-TAG709', system.label.SFM001_TAG709); //Designer 2.0 - New Tag for 'Copy of'
        tags.put('SFM001-TAG710', system.label.SFM001_TAG710); //Designer 2.0 - New Tag for 'Are you sure you want to continue?'
        tags.put('SFM001-TAG711', system.label.SFM001_TAG711); //Designer 2.0 - New Tag for 'All the changes done will be lost if you continue'
        tags.put('SFM001-TAG712', system.label.SFM001_TAG712); //Designer 2.0 - New Tag for 'Yes, continue'
        tags.put('SFM001-TAG713', system.label.SFM001_TAG713); //Designer 2.0 - New Tag for 'No, go back to changes'
        tags.put('SFM001-TAG714', system.label.SFM001_TAG714); //Designer 2.0 - New Tag for 'An error occurred while saving. Field does not exist'
        tags.put('SFM001-TAG715', system.label.SFM001_TAG715); //Designer 2.0 - New Tag for 'An error occurred while saving. Object does not exist'
        tags.put('SFM001-TAG716', system.label.SFM001_TAG716); //Designer 2.0 - New Tag for 'Invalid value'
        tags.put('SFM001-TAG717', system.label.SFM001_TAG717); //Designer 2.0 - New Tag for 'Select a field'
        tags.put('SFM001-TAG718', system.label.SFM001_TAG718); //Designer 2.0 - New Tag for 'Name must be at least 8 characters long'
        tags.put('SFM001-TAG719', system.label.SFM001_TAG719); //Designer 2.0 - New Tag for 'Following are the different areas where this expression is being used'
        tags.put('SFM001-TAG720', system.label.SFM001_TAG720); //Designer 2.0 - New Tag for 'Following are the different areas where this DVR is being used'
        tags.put('SFM001-TAG721', system.label.SFM001_TAG721); //Designer 2.0 - New Tag for 'You are about to change this'
        tags.put('SFM001-TAG722', system.label.SFM001_TAG722); //Designer 2.0 - New Tag for 'All of your changes will be lost if you cancel now'
        tags.put('SFM001-TAG723', system.label.SFM001_TAG723); //Designer 2.0 - New Tag for 'Are you sure you want to cancel?'
        tags.put('SFM001-TAG724', system.label.SFM001_TAG724); //Designer 2.0 - New Tag for 'No, go back to changes'
        tags.put('SFM001-TAG725', system.label.SFM001_TAG725); //Designer 2.0 - New Tag for 'Yes, cancel my changes'
        tags.put('SFM001-TAG726', system.label.SFM001_TAG726); //Designer 2.0 - New Tag for 'Mapping'
        tags.put('SFM001-TAG727', system.label.SFM001_TAG727); //Designer 2.0 - New Tag for 'Object is Invalid'
        tags.put('SFM001-TAG728', system.label.SFM001_TAG728); //Designer 2.0 - New Tag for 'Please Configure Atleast one Mapping'

        tags.put('SFM001-TAG728E', system.label.FSA004_TAG003); //Designer 2.0 - Existing Tag for 'Open record'
        tags.put('SFM001-TAG729', system.label.SFM001_TAG729); //Designer 2.0 - New Tag for 'Standard Mappings'

        tags.put('SFM001-TAG729E', system.label.OFFL014_TAG021); //Designer 2.0 - Existing Tag for 'Multiple records found in the lookup matching the text you have entered. Please select a record from the list'
        tags.put('SFM001-TAG730', system.label.SFM001_TAG730);  //Designer 2.0 - New Tag for 'Other Mappings'

        tags.put('SFM001-TAG730E', system.label.PRODIQ001_TAG025);  //Designer 2.0 - Reusing existing Tag for 'Enter a value'
        tags.put('SFM001-TAG731', system.label.SFM001_TAG731);  //Designer 2.0 - New Tag for 'Object and Mapping'
        tags.put('SFM001-TAG731E', system.label.IPRD002_TAG034);  //Designer 2.0 - Reusing existing Tag for 'Review all error messages below to correct your data.'

        tags.put('SFM001-TAG738', System.Label.SFM001_TAG738);
        tags.put('SFM001-TAG739', System.Label.SFM001_TAG739);
        tags.put('SFM001-TAG740', System.Label.SFM001_TAG740);
        tags.put('SFM001-TAG741', System.Label.SFM001_TAG741);
        tags.put('SFM001-TAG742', System.Label.SFM001_TAG742);
        tags.put('SFM001-TAG743', System.Label.SFM001_TAG743);
        tags.put('SFM001-TAG744', System.Label.SFM001_TAG744);
        tags.put('SFM001-TAG745', System.Label.SFM001_TAG745);
        tags.put('SFM001-TAG746', System.Label.SFM001_TAG746);
        tags.put('SFM001-TAG747', System.Label.SFM001_TAG747);
        tags.put('SFM001-TAG748', System.Label.SFM001_TAG748);
        tags.put('SFM001-TAG749', System.Label.SFM001_TAG749);
        tags.put('SFM001-TAG750', System.Label.SFM001_TAG750);
        tags.put('SFM001-TAG751', System.Label.SFM001_TAG751);
        tags.put('SFM001-TAG752', System.Label.SFM001_TAG752);
        tags.put('SFM001-TAG753', System.Label.SFM001_TAG753);
        tags.put('SFM001-TAG754', System.Label.SFM001_TAG754);
        tags.put('SFM001-TAG755', System.Label.SFM001_TAG755);
        tags.put('SFM001-TAG756', System.Label.SFM001_TAG756);
        tags.put('SFM001-TAG757', System.Label.SFM001_TAG757);
        tags.put('SFM001-TAG758', System.Label.SFM001_TAG758);
        tags.put('SFM001-TAG759', System.Label.SFM001_TAG759);
        tags.put('SFM001-TAG760', System.Label.SFM001_TAG760);
        tags.put('SFM001-TAG761', System.Label.SFM001_TAG761);
        tags.put('SFM001-TAG762', System.Label.SFM001_TAG762);
        tags.put('SFM001-TAG763', System.Label.SFM001_TAG763);
        tags.put('SFM001-TAG764', System.Label.SFM001_TAG764);
        tags.put('SFM001-TAG765', System.Label.SFM001_TAG765);
        tags.put('SFM001-TAG766', System.Label.SFM001_TAG766);
        tags.put('SFM001-TAG767', System.Label.SFM001_TAG767);
        tags.put('SFM001-TAG768', System.Label.SFM001_TAG768);
        tags.put('SFM001-TAG769', System.Label.SFM001_TAG769);
        tags.put('SFM001-TAG770', System.Label.SFM001_TAG770);
        tags.put('SFM001-TAG771', System.Label.SFM001_TAG771);
        tags.put('SFM001-TAG772', System.Label.SFM001_TAG772);
        tags.put('SFM001-TAG773', System.Label.SFM001_TAG773);
        tags.put('SFM001-TAG774', System.Label.SFM001_TAG774);
        tags.put('SFM001-TAG775', System.Label.SFM001_TAG775);
        tags.put('SFM001-TAG776', System.Label.SFM001_TAG776);
        tags.put('SFM001-TAG777', System.Label.SFM001_TAG777);
        tags.put('SFM001-TAG778', System.Label.SFM001_TAG778);
        tags.put('SFM001-TAG779', System.Label.SFM001_TAG779);
        tags.put('SFM001-TAG780', System.Label.SFM001_TAG780);
        tags.put('SFM001-TAG781', System.Label.SFM001_TAG781);
        tags.put('SFM001-TAG782', System.Label.SFM001_TAG782);
        tags.put('SFM001-TAG783', System.Label.SFM001_TAG783);
        tags.put('SFM001-TAG784', System.Label.SFM001_TAG784);
        tags.put('SFM001-TAG785', System.Label.SFM001_TAG785);
        tags.put('SFM001-TAG786', System.Label.SFM001_TAG786);
        tags.put('SFM001-TAG787', System.Label.SFM001_TAG787);
        tags.put('SFM001-TAG788', System.Label.SFM001_TAG788);
        tags.put('SFM001-TAG789', System.Label.SFM001_TAG789);
        tags.put('SFM001-TAG790', System.Label.SFM001_TAG790);
        tags.put('SFM001-TAG791', System.Label.SFM001_TAG791);
        tags.put('SFM001-TAG792', System.Label.SFM001_TAG792);
        tags.put('SFM001-TAG793', System.Label.SFM001_TAG793);
        tags.put('SFM001-TAG794', System.Label.SFM001_TAG794);
        tags.put('SFM001-TAG795', System.Label.SFM001_TAG795);
        tags.put('SFM001-TAG796', System.Label.SFM001_TAG796);
        tags.put('SFM001-TAG797', System.Label.SFM001_TAG797);
        tags.put('SFM001-TAG798', System.Label.SFM001_TAG798);
        tags.put('SFM001-TAG799', System.Label.SFM001_TAG799);
        tags.put('SFM001-TAG800', System.Label.SFM001_TAG800);
        tags.put('SFM001-TAG801', System.Label.SFM001_TAG801);
        tags.put('SFM001-TAG802', System.Label.SFM001_TAG802);
        tags.put('SFM001-TAG803', System.Label.SFM001_TAG803);
        tags.put('SFM001-TAG804', System.Label.SFM001_TAG804);
        tags.put('SFM001-TAG805', System.Label.SFM001_TAG805);
        tags.put('SFM001-TAG806', System.Label.SFM001_TAG806);
        tags.put('SFM001-TAG807', System.Label.SFM001_TAG807);
        tags.put('SFM001-TAG808', System.Label.SFM001_TAG808);
        tags.put('SFM001-TAG809', System.Label.SFM001_TAG809);
        tags.put('SFM001-TAG810', System.Label.SFM001_TAG810);
        tags.put('SFM001-TAG811', System.Label.SFM001_TAG811);
        tags.put('SFM001-TAG812', System.Label.SFM001_TAG812);
        tags.put('SFM001-TAG813', System.Label.SFM001_TAG813);
        tags.put('SFM001-TAG814', System.Label.SFM001_TAG814);
        tags.put('SFM001-TAG815', System.Label.SFM001_TAG815);
        tags.put('SFM001-TAG816', System.Label.SFM001_TAG816);
        tags.put('SFM001-TAG817', System.Label.SFM001_TAG817);
        tags.put('SFM001-TAG818', System.Label.SFM001_TAG818);
        tags.put('SFM001-TAG819', System.Label.SFM001_TAG819);
        tags.put('SFM001-TAG820', System.Label.SFM001_TAG820);
        tags.put('SFM001-TAG821', System.Label.SFM001_TAG821);
        tags.put('SFM001-TAG822', System.Label.SFM001_TAG822);
        tags.put('SFM001-TAG823', System.Label.SFM001_TAG823);
        tags.put('SFM001-TAG824', System.Label.SFM001_TAG824);
        tags.put('SFM001-TAG825', System.Label.SFM001_TAG825);
        tags.put('SFM001-TAG826', System.Label.SFM001_TAG826);
        tags.put('SFM001-TAG827', System.Label.SFM001_TAG827);
        tags.put('SFM001-TAG828', System.Label.SFM001_TAG828);
        tags.put('SFM001-TAG829', System.Label.SFM001_TAG829);
        tags.put('SFM001-TAG830', System.Label.SFM001_TAG830);
        tags.put('SFM001-TAG831', System.Label.SFM001_TAG831);
        tags.put('SFM001-TAG832', System.Label.SFM001_TAG832);
        tags.put('SFM001-TAG833', System.Label.SFM001_TAG833);
        tags.put('SFM001-TAG834', System.Label.SFM001_TAG834);
        tags.put('SFM001-TAG835', System.Label.SFM001_TAG835);
        tags.put('SFM001-TAG836', System.Label.SFM001_TAG836);
        tags.put('SFM001-TAG837', System.Label.SFM001_TAG837);
        tags.put('SFM001-TAG838', System.Label.SFM001_TAG838);
        tags.put('SFM001-TAG839', System.Label.SFM001_TAG839);
        tags.put('SFM001-TAG840', System.Label.SFM001_TAG840);
        tags.put('SFM001-TAG841', System.Label.SFM001_TAG841);
        tags.put('SFM001-TAG842', System.Label.SFM001_TAG842);
        tags.put('SFM001-TAG843', System.Label.SFM001_TAG843);
        tags.put('SFM001-TAG844', System.Label.SFM001_TAG844);
        tags.put('SFM001-TAG845', System.Label.SFM001_TAG845);
        tags.put('SFM001-TAG846', System.Label.SFM001_TAG846);
        tags.put('SFM001-TAG847', System.Label.SFM001_TAG847);
        tags.put('SFM001-TAG848', System.Label.SFM001_TAG848);
        tags.put('SFM001-TAG849', System.Label.SFM001_TAG849);
        tags.put('SFM001-TAG850', System.Label.SFM001_TAG850);
        tags.put('SFM001-TAG851', System.Label.SFM001_TAG851);
        tags.put('SFM001-TAG852', System.Label.SFM001_TAG852);
        tags.put('SFM001-TAG853', System.Label.SFM001_TAG853);
        tags.put('SFM001-TAG854', System.Label.SFM001_TAG854);
        tags.put('SFM001-TAG855', System.Label.SFM001_TAG855);
        tags.put('SFM001-TAG856', System.Label.SFM001_TAG856);
        tags.put('SFM001-TAG857', System.Label.SFM001_TAG857);
        tags.put('SFM001-TAG858', System.Label.SFM001_TAG858);
        tags.put('SFM001-TAG859', System.Label.SFM001_TAG859);
        tags.put('SFM001-TAG860', System.Label.SFM001_TAG860);
        tags.put('SFM001-TAG861', System.Label.SFM001_TAG861);
        tags.put('SFM001-TAG862', System.Label.SFM001_TAG862);
        tags.put('SFM001-TAG863', System.Label.SFM001_TAG863);
        tags.put('SFM001-TAG864', System.Label.SFM001_TAG864);
        tags.put('SFM001-TAG865', System.Label.SFM001_TAG865);
        tags.put('SFM001-TAG866', System.Label.SFM001_TAG866);
        tags.put('SFM001-TAG867', System.Label.SFM001_TAG867);
        tags.put('SFM001-TAG868', System.Label.SFM001_TAG868);
        tags.put('SFM001-TAG869', System.Label.SFM001_TAG869);
        tags.put('SFM001-TAG870', System.Label.SFM001_TAG870);
        tags.put('SFM001-TAG871', System.Label.SFM001_TAG871);
        tags.put('SFM001-TAG872', System.Label.SFM001_TAG872);
        tags.put('SFM001-TAG873', System.Label.SFM001_TAG873);
        tags.put('SFM001-TAG874', System.Label.SFM001_TAG874);
        tags.put('SFM001-TAG875', System.Label.SFM001_TAG875);
        tags.put('SFM001-TAG876', System.Label.SFM001_TAG876);
        tags.put('SFM001-TAG877', System.Label.SFM001_TAG877);
        tags.put('SFM001-TAG878', System.Label.SFM001_TAG878);
        tags.put('SFM001-TAG879', System.Label.SFM001_TAG879);
        tags.put('SFM001-TAG880', System.Label.SFM001_TAG880);
        tags.put('SFM001-TAG881', System.Label.SFM001_TAG881);
        tags.put('SFM001-TAG882', System.Label.SFM001_TAG882);
        tags.put('SFM001-TAG883', System.Label.SFM001_TAG883);
        tags.put('SFM001-TAG884', System.Label.SFM001_TAG884);
        tags.put('SFM001-TAG885', System.Label.SFM001_TAG885);
        tags.put('SFM001-TAG886', System.Label.SFM001_TAG886);
        tags.put('SFM001-TAG887', System.Label.SFM001_TAG887);
        tags.put('SFM001-TAG888', System.Label.SFM001_TAG888);
        tags.put('SFM001-TAG889', System.Label.SFM001_TAG889);
        tags.put('SFM001-TAG890', System.Label.SFM001_TAG890);
        tags.put('SFM001-TAG891', System.Label.SFM001_TAG891);
        tags.put('SFM001-TAG892', System.Label.SFM001_TAG892);
        tags.put('SFM001-TAG893', System.Label.SFM001_TAG893);
        tags.put('SFM001-TAG894', System.Label.SFM001_TAG894);
        tags.put('SFM001-TAG895', System.Label.SFM001_TAG895);
        tags.put('SFM001-TAG896', System.Label.SFM001_TAG896);
        tags.put('SFM001-TAG897', System.Label.SFM001_TAG897);
        tags.put('SFM001-TAG898', System.Label.SFM001_TAG898);
        tags.put('SFM001-TAG899', System.Label.SFM001_TAG899);
        tags.put('SFM001-TAG900', System.Label.SFM001_TAG900);
        tags.put('SFM001-TAG901', System.Label.SFM001_TAG901);
        tags.put('SFM001-TAG902', System.Label.SFM001_TAG902);
        tags.put('SFM001-TAG903', System.Label.SFM001_TAG903);
        tags.put('SFM001-TAG904', System.Label.SFM001_TAG904);
        tags.put('SFM001-TAG905', System.Label.SFM001_TAG905);
        tags.put('SFM001-TAG906', System.Label.SFM001_TAG906);
        tags.put('SFM001-TAG907', System.Label.SFM001_TAG907);
        tags.put('SFM001-TAG908', System.Label.SFM001_TAG908);
        tags.put('SFM001-TAG909', System.Label.SFM001_TAG909);
        tags.put('SFM001-TAG910', System.Label.SFM001_TAG910);
        tags.put('SFM001-TAG911', System.Label.SFM001_TAG911);
        tags.put('SFM001-TAG912', System.Label.SFM001_TAG912);
        tags.put('SFM001-TAG913', System.Label.SFM001_TAG913);
        tags.put('SFM001-TAG914', System.Label.SFM001_TAG914);
        tags.put('SFM001-TAG915', System.Label.SFM001_TAG915);
        tags.put('SFM001-TAG916', System.Label.SFM001_TAG916);
        tags.put('SFM001-TAG917', System.Label.SFM001_TAG917);
        tags.put('SFM001-TAG918', System.Label.SFM001_TAG918);
        tags.put('SFM001-TAG919', System.Label.SFM001_TAG919);
        tags.put('SFM001-TAG920', System.Label.SFM001_TAG920);
        tags.put('SFM001-TAG921', System.Label.SFM001_TAG921);
        tags.put('SFM001-TAG922', System.Label.SFM001_TAG922);
        tags.put('SFM001-TAG923', System.Label.SFM001_TAG923);
        tags.put('SFM001-TAG924', System.Label.SFM001_TAG924);
        tags.put('SFM001-TAG925', System.Label.SFM001_TAG925);
        tags.put('SFM001-TAG926', System.Label.SFM001_TAG926);
        tags.put('SFM001-TAG927', System.Label.SFM001_TAG927);
        tags.put('SFM001-TAG928', System.Label.SFM001_TAG928);
        tags.put('SFM001-TAG929', System.Label.SFM001_TAG929);
        tags.put('SFM001-TAG930', System.Label.SFM001_TAG930);
        tags.put('SFM001-TAG931', System.Label.SFM001_TAG931);
        tags.put('SFM001-TAG932', System.Label.SFM001_TAG932);
        tags.put('SFM001-TAG933', System.Label.SFM001_TAG933);
        tags.put('SFM001-TAG934', System.Label.SFM001_TAG934);
        tags.put('SFM001-TAG935', System.Label.SFM001_TAG935);
        tags.put('SFM001-TAG936', System.Label.SFM001_TAG936);
        tags.put('SFM001-TAG937', System.Label.SFM001_TAG937);
        tags.put('SFM001-TAG938', System.Label.SFM001_TAG938);
        tags.put('SFM001-TAG939', System.Label.SFM001_TAG939);
        tags.put('SFM001-TAG940', System.Label.SFM001_TAG940);
        tags.put('SFM001-TAG941', System.Label.SFM001_TAG941);
        tags.put('SFM001-TAG942', System.Label.SFM001_TAG942);
        tags.put('SFM001-TAG943', System.Label.SFM001_TAG943);
        tags.put('SFM001-TAG944', System.Label.SFM001_TAG944);
        tags.put('SFM001-TAG945', System.Label.SFM001_TAG945);
        tags.put('SFM001-TAG946', System.Label.SFM001_TAG946);
        tags.put('SFM001-TAG947', System.Label.SFM001_TAG947);
        tags.put('SFM001-TAG948', System.Label.SFM001_TAG948);
        tags.put('SFM001-TAG949', System.Label.SFM001_TAG949);
        tags.put('SFM001-TAG950', System.Label.SFM001_TAG950);
        tags.put('SFM001-TAG951', System.Label.SFM001_TAG951);
        tags.put('SFM001-TAG952', System.Label.SFM001_TAG952);
        tags.put('SFM001-TAG953', System.Label.SFM001_TAG953);
        tags.put('SFM001-TAG954', System.Label.SFM001_TAG954);
        tags.put('SFM001-TAG955', System.Label.SFM001_TAG955);
        tags.put('SFM001-TAG956', System.Label.SFM001_TAG956);
        tags.put('SFM001-TAG957', System.Label.SFM001_TAG957);
        tags.put('SFM001-TAG958', System.Label.SFM001_TAG958);
        tags.put('SFM001-TAG959', System.Label.SFM001_TAG959);
        tags.put('SFM001-TAG960', System.Label.SFM001_TAG960);
        tags.put('SFM001-TAG961', System.Label.SFM001_TAG961);
        tags.put('SFM001-TAG962', System.Label.SFM001_TAG962);
        tags.put('SFM001-TAG963', System.Label.SFM001_TAG963);
        tags.put('SFM001-TAG964', System.Label.SFM001_TAG964);
        tags.put('SFM001-TAG965', System.Label.SFM001_TAG965);
        tags.put('SFM001-TAG966', System.Label.SFM001_TAG966);
        tags.put('SFM001-TAG967', System.Label.SFM001_TAG967);
        tags.put('SFM001-TAG968', System.Label.SFM001_TAG968);
        tags.put('SFM001-TAG969', System.Label.SFM001_TAG969);
        tags.put('SFM001-TAG970', System.Label.SFM001_TAG970);
        tags.put('SFM001-TAG971', System.Label.SFM001_TAG971);
        tags.put('SFM001-TAG972', System.Label.SFM001_TAG972);
        tags.put('SFM001-TAG973', System.Label.SFM001_TAG973);
        tags.put('SFM001-TAG974', System.Label.SFM001_TAG974);
        tags.put('SFM001-TAG975', System.Label.SFM001_TAG975);  
        tags.put('SFM001-TAG976', System.Label.SFM001_TAG976);
        tags.put('SFM001-TAG977', System.Label.SFM001_TAG977);
        tags.put('SFM001-TAG978', System.Label.SFM001_TAG978);
        tags.put('SFM001-TAG979', System.Label.SFM001_TAG979);
        tags.put('SFM001-TAG980', System.Label.SFM001_TAG980);               
        tags.put('SFM001-TAG981', System.Label.SFM001_TAG981);
        tags.put('SFM001-TAG982', System.Label.SFM001_TAG982);
        tags.put('SFM001-TAG983', System.Label.SFM001_TAG983);
        tags.put('SFM001-TAG984', System.Label.SFM001_TAG984);
        tags.put('SFM001-TAG985', System.Label.SFM001_TAG985);
        tags.put('SFM001-TAG986', System.Label.SFM001_TAG986);
        tags.put('SFM001-TAG987', System.Label.SFM001_TAG987);
        tags.put('SFM001-TAG988', System.Label.SFM001_TAG988);
        tags.put('SFM001-TAG989', System.Label.SFM001_TAG989);
        tags.put('SFM001-TAG990', System.Label.SFM001_TAG990);
        tags.put('SFM001-TAG991', System.Label.SFM001_TAG991);
        tags.put('SFM001-TAG992', System.Label.SFM001_TAG992);
        tags.put('SFM001-TAG993', System.Label.SFM001_TAG993);
        tags.put('SFM001-TAG994', System.Label.SFM001_TAG994);
        tags.put('SFM001-TAG995', System.Label.SFM001_TAG995);
    }
    
    public static void getChecklistTags(Map<String,String> tags) {
        tags.put('CHK001-TAG001', System.Label.CHK001_TAG001);
        tags.put('CHK001-TAG002', System.Label.CHK001_TAG002);
        tags.put('CHK001-TAG003', System.Label.CHK001_TAG003);
        tags.put('CHK001-TAG004', System.Label.CHK001_TAG004);
        tags.put('CHK001-TAG005', System.Label.CHK001_TAG005);
        tags.put('CHK001-TAG006', System.Label.CHK001_TAG006);
        tags.put('CHK001-TAG007', System.Label.CHK001_TAG007);
        tags.put('CHK001-TAG008', System.Label.CHK001_TAG008);
        tags.put('CHK001-TAG009', System.Label.CHK001_TAG009);
        tags.put('CHK001-TAG010', System.Label.CHK001_TAG010);
        tags.put('CHK001-TAG011', System.Label.CHK001_TAG011);
        tags.put('CHK001-TAG012', System.Label.CHK001_TAG012);
        tags.put('CHK001-TAG013', System.Label.CHK001_TAG013);
        tags.put('CHK001-TAG014', System.Label.CHK001_TAG014);
        tags.put('CHK001-TAG015', System.Label.CHK001_TAG015);
        tags.put('CHK001-TAG016', System.Label.CHK001_TAG016);
        tags.put('CHK001-TAG017', System.Label.CHK001_TAG017);
        tags.put('CHK001-TAG018', System.Label.CHK001_TAG018);
        tags.put('CHK001-TAG019', System.Label.CHK001_TAG019);
        tags.put('CHK001-TAG020', System.Label.CHK001_TAG020);
        tags.put('CHK001-TAG021', System.Label.CHK001_TAG021);
        tags.put('CHK001-TAG022', System.Label.CHK001_TAG022);
        tags.put('CHK001-TAG023', System.Label.CHK001_TAG023);
        tags.put('CHK001-TAG024', System.Label.CHK001_TAG024);
        tags.put('CHK001-TAG025', System.Label.CHK001_TAG025);
        tags.put('CHK001-TAG026', System.Label.CHK001_TAG026);
        tags.put('CHK001-TAG027', System.Label.CHK001_TAG027);
        tags.put('CHK001-TAG028', System.Label.CHK001_TAG028);
        tags.put('CHK001-TAG029', System.Label.CHK001_TAG029);
        tags.put('CHK001-TAG030', System.Label.CHK001_TAG030);
        tags.put('CHK001-TAG031', System.Label.CHK001_TAG031);
        tags.put('CHK001-TAG032', System.Label.CHK001_TAG032);
        tags.put('CHK001-TAG033', System.Label.CHK001_TAG033);
        tags.put('CHK001-TAG034', System.Label.CHK001_TAG034);
        tags.put('CHK001-TAG035', System.Label.CHK001_TAG035);
        tags.put('CHK001-TAG036', System.Label.CHK001_TAG036);
        tags.put('CHK001-TAG037', System.Label.CHK001_TAG037);
        tags.put('CHK001-TAG038', System.Label.CHK001_TAG038);
        tags.put('CHK001-TAG039', System.Label.CHK001_TAG039);
        tags.put('CHK001-TAG040', System.Label.CHK001_TAG040);
        tags.put('CHK001-TAG041', System.Label.CHK001_TAG041);
        tags.put('CHK001-TAG042', System.Label.CHK001_TAG042);
        tags.put('CHK001-TAG043', System.Label.CHK001_TAG043);
        tags.put('CHK001-TAG044', System.Label.CHK001_TAG044);
        tags.put('CHK001-TAG045', System.Label.CHK001_TAG045);
        tags.put('CHK001-TAG046', System.Label.CHK001_TAG046);
        tags.put('CHK001-TAG047', System.Label.CHK001_TAG047);
        tags.put('CHK001-TAG048', System.Label.CHK001_TAG048);
        tags.put('CHK001-TAG049', System.Label.CHK001_TAG049);
        tags.put('CHK001-TAG050', System.Label.CHK001_TAG050);
        tags.put('CHK001-TAG051', System.Label.CHK001_TAG051);
        tags.put('CHK001-TAG052', System.Label.CHK001_TAG052);
        tags.put('CHK001-TAG053', System.Label.CHK001_TAG053);
        tags.put('CHK001-TAG054', System.Label.CHK001_TAG054);
        tags.put('CHK001-TAG055', System.Label.CHK001_TAG055);
        tags.put('CHK001-TAG056', System.Label.CHK001_TAG056);
        tags.put('CHK001-TAG057', System.Label.CHK001_TAG057);
        tags.put('CHK001-TAG058', System.Label.CHK001_TAG058);
        tags.put('CHK001-TAG059', System.Label.CHK001_TAG059);
        tags.put('CHK001-TAG060', System.Label.CHK001_TAG060);
        tags.put('CHK001-TAG061', System.Label.CHK001_TAG061);
        tags.put('CHK001-TAG062', System.Label.CHK001_TAG062);
        tags.put('CHK001-TAG063', System.Label.CHK001_TAG063);
        tags.put('CHK001-TAG064', System.Label.CHK001_TAG064);
        tags.put('CHK001-TAG065', System.Label.CHK001_TAG065);
        tags.put('CHK001-TAG066', System.Label.CHK001_TAG066);
        tags.put('CHK001-TAG067', System.Label.CHK001_TAG067);
        tags.put('CHK001-TAG068', System.Label.CHK001_TAG068);
        tags.put('CHK001-TAG069', System.Label.CHK001_TAG069);
        tags.put('CHK001-TAG070', System.Label.CHK001_TAG070);
        tags.put('CHK001-TAG071', System.Label.CHK001_TAG071);
        tags.put('CHK001-TAG072', System.Label.CHK001_TAG072);
        tags.put('CHK001-TAG073', System.Label.CHK001_TAG073);
        tags.put('CHK001-TAG074', System.Label.CHK001_TAG074);
        tags.put('CHK001-TAG075', System.Label.CHK001_TAG075);
    }
}