@isTest
private class SFMWizardDelivery_UT {
	
	static testMethod void getWizardInfo_REST_test(){
		/*RestRequest req = new RestRequest(); 
		RestResponse res = new RestResponse();
		
		req.requestURI = '';  
		req.httpMe1thod = 'POST';
		RestContext.request = req;
		RestContext.response = res;
		
		SVMXC.SFMWizardDeliveryServiceIntf.doPost();*/
	}
	
	static testMethod void getWizardInfo_JSR_test(){
		/*SVMXC.SFMWizardDeliveryTestController.JsrGetWizardInfo(
		'{"RecordId":"","ActionTypes":[]}'
		);*/
	}
}